[package]
name = "java-linguo"
version = "0.6.2"
description = "Percorso desktop per imparare Java con teoria, verifica e laboratorio"
authors = ["Federpelli25"]
edition = "2021"

[lib]
name = "java_linguo_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "=2.6.3", features = [] }

[dependencies]
serde_json = "=1.0.151"
tauri = { version = "=2.11.5", features = [] }
tauri-plugin-shell = "=2.3.6"
tauri-plugin-updater = "=2.11.0"
tauri-plugin-process = "=2.3.1"
