import type { CourseManifestItem } from './course-types';

export const courseManifest: CourseManifestItem[] = [
  { number: '01', title: 'Stringhe, cicli e casi limite', area: 'Fondamenti e problem solving', level: 'Fondamenti', minimumJdk: '17', duration: '60–75 min' },
  { number: '02', title: 'Metodi, parametri, scope e debug', area: 'Fondamenti e problem solving', level: 'Fondamenti', minimumJdk: '17', duration: '70–90 min' },
  { number: '03', title: 'Tipi, variabili e conversioni', area: 'Fondamenti e problem solving', level: 'Fondamenti', minimumJdk: '17', duration: '70–90 min' },
  { number: '04', title: 'Decisioni, logica booleana e switch', area: 'Fondamenti e problem solving', level: 'Fondamenti', minimumJdk: '17', duration: '70–90 min' },
  { number: '05', title: 'Cicli, invarianti e terminazione', area: 'Fondamenti e problem solving', level: 'Fondamenti', minimumJdk: '17', duration: '70–90 min' },
  { number: '06', title: 'Ricorsione e stack delle chiamate', area: 'Fondamenti e problem solving', level: 'Fondamenti', minimumJdk: '17', duration: '70–90 min' },
  { number: '07', title: 'Array, memoria e attraversamento', area: 'Dati e algoritmi', level: 'Fondamenti', minimumJdk: '17', duration: '70–90 min' },
  { number: '08', title: 'List e ArrayList', area: 'Dati e algoritmi', level: 'Fondamenti', minimumJdk: '17', duration: '70–90 min' },
  { number: '09', title: 'Set, uguaglianza e unicità', area: 'Dati e algoritmi', level: 'Intermedio', minimumJdk: '17', duration: '85–110 min' },
  { number: '10', title: 'Map e indicizzazione per chiave', area: 'Dati e algoritmi', level: 'Intermedio', minimumJdk: '17', duration: '85–110 min' },
  { number: '11', title: 'Iteratori, ordinamento e Comparator', area: 'Dati e algoritmi', level: 'Intermedio', minimumJdk: '17', duration: '85–110 min' },
  { number: '12', title: 'Complessità, ricerca e scelta delle strutture', area: 'Dati e algoritmi', level: 'Intermedio', minimumJdk: '17', duration: '85–110 min' },
  { number: '13', title: 'Classi, oggetti e incapsulamento', area: 'Modellazione a oggetti', level: 'Intermedio', minimumJdk: '17', duration: '85–110 min' },
  { number: '14', title: 'Costruttori, invarianti e immutabilità', area: 'Modellazione a oggetti', level: 'Intermedio', minimumJdk: '17', duration: '85–110 min' },
  { number: '15', title: 'Composizione e dipendenze', area: 'Modellazione a oggetti', level: 'Intermedio', minimumJdk: '17', duration: '85–110 min' },
  { number: '16', title: 'Ereditarietà e polimorfismo', area: 'Modellazione a oggetti', level: 'Intermedio', minimumJdk: '17', duration: '85–110 min' },
  { number: '17', title: 'Interfacce e metodi default', area: 'Modellazione a oggetti', level: 'Intermedio', minimumJdk: '17', duration: '85–110 min' },
  { number: '18', title: 'Enum, record e oggetti valore', area: 'Modellazione a oggetti', level: 'Intermedio', minimumJdk: '17', duration: '85–110 min' },
  { number: '19', title: 'Sealed classes e pattern matching', area: 'Modellazione a oggetti', level: 'Intermedio', minimumJdk: '21', duration: '85–110 min' },
  { number: '20', title: 'Eccezioni e contratti d’errore', area: 'Robustezza e libreria standard', level: 'Intermedio', minimumJdk: '17', duration: '85–110 min' },
  { number: '21', title: 'Path, Files e gestione delle risorse', area: 'Robustezza e libreria standard', level: 'Intermedio', minimumJdk: '17', duration: '85–110 min' },
  { number: '22', title: 'Stream di byte, caratteri e buffering', area: 'Robustezza e libreria standard', level: 'Intermedio', minimumJdk: '17', duration: '85–110 min' },
  { number: '23', title: 'Date, tempo e fusi orari', area: 'Robustezza e libreria standard', level: 'Intermedio', minimumJdk: '17', duration: '85–110 min' },
  { number: '24', title: 'Regex, Unicode e testo affidabile', area: 'Robustezza e libreria standard', level: 'Intermedio', minimumJdk: '17', duration: '85–110 min' },
  { number: '25', title: 'Numeri, BigDecimal e casualità', area: 'Robustezza e libreria standard', level: 'Intermedio', minimumJdk: '17', duration: '85–110 min' },
  { number: '26', title: 'Generics e sicurezza dei tipi', area: 'Astrazioni e stile funzionale', level: 'Intermedio', minimumJdk: '17', duration: '85–110 min' },
  { number: '27', title: 'Bound, wildcard e principio PECS', area: 'Astrazioni e stile funzionale', level: 'Intermedio', minimumJdk: '17', duration: '85–110 min' },
  { number: '28', title: 'Annotazioni e reflection', area: 'Astrazioni e stile funzionale', level: 'Avanzato', minimumJdk: '17', duration: '100–130 min' },
  { number: '29', title: 'Lambda e interfacce funzionali', area: 'Astrazioni e stile funzionale', level: 'Intermedio', minimumJdk: '17', duration: '85–110 min' },
  { number: '30', title: 'Stream: pipeline e valutazione lazy', area: 'Astrazioni e stile funzionale', level: 'Intermedio', minimumJdk: '17', duration: '85–110 min' },
  { number: '31', title: 'Collector, Optional e composizione', area: 'Astrazioni e stile funzionale', level: 'Intermedio', minimumJdk: '17', duration: '85–110 min' },
  { number: '32', title: 'Thread, race condition e visibilità', area: 'Concorrenza e JVM', level: 'Avanzato', minimumJdk: '17', duration: '100–130 min' },
  { number: '33', title: 'Monitor, lock e operazioni atomiche', area: 'Concorrenza e JVM', level: 'Avanzato', minimumJdk: '17', duration: '100–130 min' },
  { number: '34', title: 'ExecutorService e Future', area: 'Concorrenza e JVM', level: 'Avanzato', minimumJdk: '17', duration: '100–130 min' },
  { number: '35', title: 'CompletableFuture e pipeline asincrone', area: 'Concorrenza e JVM', level: 'Avanzato', minimumJdk: '17', duration: '100–130 min' },
  { number: '36', title: 'Virtual thread e carichi bloccanti', area: 'Concorrenza e JVM', level: 'Avanzato', minimumJdk: '21', duration: '100–130 min' },
  { number: '37', title: 'Collezioni concorrenti e Java Memory Model', area: 'Concorrenza e JVM', level: 'Avanzato', minimumJdk: '17', duration: '100–130 min' },
  { number: '38', title: 'Package, moduli e JAR', area: 'Ingegneria Java', level: 'Intermedio', minimumJdk: '17', duration: '85–110 min' },
  { number: '39', title: 'Test automatici e sviluppo guidato dai test', area: 'Ingegneria Java', level: 'Intermedio', minimumJdk: '17', duration: '85–110 min' },
  { number: '40', title: 'Maven, Gradle e dipendenze riproducibili', area: 'Ingegneria Java', level: 'Intermedio', minimumJdk: '17', duration: '85–110 min' },
  { number: '41', title: 'Logging, diagnostica e osservabilità', area: 'Ingegneria Java', level: 'Intermedio', minimumJdk: '17', duration: '85–110 min' },
  { number: '42', title: 'JDBC, transazioni e consistenza', area: 'Ingegneria Java', level: 'Avanzato', minimumJdk: '17', duration: '100–130 min' },
  { number: '43', title: 'HTTP Client, protocolli e JSON', area: 'Ingegneria Java', level: 'Avanzato', minimumJdk: '17', duration: '100–130 min' },
  { number: '44', title: 'Secure coding e gestione della configurazione', area: 'Ingegneria Java', level: 'Avanzato', minimumJdk: '17', duration: '100–130 min' },
  { number: '45', title: 'Memoria JVM e garbage collection', area: 'Java moderno e prestazioni', level: 'Avanzato', minimumJdk: '17', duration: '100–130 min' },
  { number: '46', title: 'Profilazione, JFR e misurazione', area: 'Java moderno e prestazioni', level: 'Avanzato', minimumJdk: '17', duration: '100–130 min' },
  { number: '47', title: 'Java 21: pattern e collezioni sequenziate', area: 'Java moderno e prestazioni', level: 'Avanzato', minimumJdk: '21', duration: '100–130 min' },
  { number: '48', title: 'Java 25 e governo delle feature preview', area: 'Java moderno e prestazioni', level: 'Avanzato', minimumJdk: '25', duration: '100–130 min' },
  { number: '49', title: 'Capstone: biblioteca a oggetti', area: 'Progetti conclusivi', level: 'Progetto', minimumJdk: '21', duration: '150–210 min' },
  { number: '50', title: 'Capstone: analizzatore di file', area: 'Progetti conclusivi', level: 'Progetto', minimumJdk: '21', duration: '150–210 min' },
  { number: '51', title: 'Capstone: aggregatore concorrente', area: 'Progetti conclusivi', level: 'Progetto', minimumJdk: '21', duration: '150–210 min' },
  { number: '52', title: 'Capstone finale: applicazione stratificata', area: 'Progetti conclusivi', level: 'Progetto', minimumJdk: '25', duration: '150–210 min' },
];
