import { createLesson } from './course-factory';

const api = (label: string, path: string) => ({ label, url: `https://docs.oracle.com/en/java/javase/25/docs/api/${path}` });
const jls = (label: string, chapter: string) => ({ label, url: `https://docs.oracle.com/javase/specs/jls/se25/html/${chapter}` });

export const lessons20to37 = [
  createLesson({
    number: '20', title: 'Eccezioni e contratti d’errore', area: 'Robustezza e libreria standard', level: 'Intermedio', minimumJdk: '17', keywords: ['Exception', 'checked', 'unchecked', 'try-with-resources'],
    definition: 'Un’eccezione trasferisce il controllo quando un contratto non può essere completato; il tipo scelto comunica se il chiamante può ragionevolmente recuperare.',
    mentalModel: 'L’eccezione risale i frame finché trova un handler compatibile; finally e try-with-resources gestiscono il rilascio indipendentemente dall’esito.',
    analogy: 'Un protocollo di emergenza interrompe il flusso normale e consegna informazioni al primo responsabile in grado di intervenire.',
    syntax: 'try (var reader = Files.newBufferedReader(path)) {\n    return reader.readLine();\n}',
    example: 'try { Integer.parseInt("x"); }\ncatch (NumberFormatException error) { System.out.println("non valido"); }',
    edgeRule: 'Non catturare Exception genericamente se non puoi recuperare; conserva causa e contesto quando traduci un errore.',
    tradeoff: 'Le checked exception rendono visibile il recupero nel tipo, ma possono propagare rumore; le unchecked segnalano spesso violazioni di contratto.',
    commonError: 'Catturare un’eccezione, ignorarla e continuare con uno stato incompleto.', source: jls('JLS §11 — Exceptions', 'jls-11.html'),
    lab: { method: 'parsePort', title: 'Valida una porta', signature: 'static int parsePort(String text)', scenario: 'Una configurazione riceve la porta come testo e deve produrre un errore utile.', goal: 'Converti il testo in una porta 1–65535 traducendo errori sintattici in IllegalArgumentException con causa.', main: 'System.out.println(parsePort("8080"));', stub: 'static int parsePort(String text) {\n        // TODO: valida, converti e conserva la causa\n        return 0;\n    }', cases: [{ input: '"8080"', output: '8080', purpose: 'Valore normale.' }, { input: '"65536"', output: 'IllegalArgumentException', purpose: 'Fuori intervallo.' }, { input: '"otto" / null', output: 'IllegalArgumentException', purpose: 'Formato e assenza.' }], reflection: 'Quale informazione perderesti omettendo la causa originale?', challenge: 'Definisci un tipo di eccezione di configurazione con il nome della proprietà.' },
  }),
  createLesson({
    number: '21', title: 'Path, Files e gestione delle risorse', area: 'Robustezza e libreria standard', level: 'Intermedio', minimumJdk: '17', keywords: ['Path', 'Files', 'risorsa', 'filesystem'],
    definition: 'Path rappresenta un percorso senza garantire che esista; Files esegue operazioni sul filesystem e try-with-resources chiude le risorse aperte.',
    mentalModel: 'Separa costruzione del nome, risoluzione del percorso, verifica e operazione I/O. Ogni passaggio può fallire per ragioni differenti.',
    analogy: 'Un indirizzo non garantisce che l’edificio esista o che tu abbia la chiave per entrarvi.',
    syntax: 'Path file = base.resolve("notes.txt").normalize();\nString text = Files.readString(file);',
    example: 'Path base = Path.of("data").toAbsolutePath();\nSystem.out.println(base.resolve("report.txt"));',
    edgeRule: 'Normalizzare non rende sicuro un percorso: dopo resolve verifica che il risultato resti sotto la directory autorizzata.',
    tradeoff: 'readString è semplice per file piccoli; streaming e buffering evitano di caricare file grandi interamente in memoria.',
    commonError: 'Concatenare percorsi come String e ignorare separatori, normalizzazione o attraversamento con ..', source: api('API Files — Java SE 25', 'java.base/java/nio/file/Files.html'),
    lab: { method: 'safeResolve', title: 'Risolvi un percorso confinato', signature: 'static java.nio.file.Path safeResolve(java.nio.file.Path base, String relative)', scenario: 'Un importatore deve accettare nomi relativi senza permettere di uscire dalla cartella assegnata.', goal: 'Risolvi e normalizza il percorso e rifiutalo se non inizia con la base assoluta normalizzata.', main: 'System.out.println(safeResolve(java.nio.file.Path.of("data"), "notes.txt"));', stub: 'static java.nio.file.Path safeResolve(java.nio.file.Path base, String relative) {\n        // TODO: normalizza base e risultato, poi verifica startsWith\n        return base;\n    }', cases: [{ input: 'data + notes.txt', output: 'percorso sotto data', purpose: 'Caso normale.' }, { input: 'data + .', output: 'data', purpose: 'Percorso minimo.' }, { input: 'data + ../secret.txt', output: 'IllegalArgumentException', purpose: 'Tentativo di uscita.' }], reflection: 'Perché normalize senza startsWith non è una barriera di sicurezza?', challenge: 'Valuta i collegamenti simbolici e spiega quando serve toRealPath.' },
  }),
  createLesson({
    number: '22', title: 'Stream di byte, caratteri e buffering', area: 'Robustezza e libreria standard', level: 'Intermedio', minimumJdk: '17', keywords: ['InputStream', 'Reader', 'charset', 'buffer'],
    definition: 'Gli stream di byte trasportano dati grezzi; Reader e Writer interpretano caratteri tramite un charset esplicito.',
    mentalModel: 'I byte arrivano in blocchi; il decoder può aver bisogno di più byte per produrre un carattere. Il buffer separa dimensione logica e letture fisiche.',
    analogy: 'I byte sono casse numerate; il charset è il catalogo necessario per ricostruire correttamente il contenuto testuale.',
    syntax: 'try (Reader reader = Files.newBufferedReader(path, StandardCharsets.UTF_8)) { /* leggi */ }',
    example: 'byte[] encoded = "caffè".getBytes(StandardCharsets.UTF_8);\nString decoded = new String(encoded, StandardCharsets.UTF_8);',
    edgeRule: 'Non assumere che una chiamata read riempia il buffer; -1 indica fine stream e 0 non equivale necessariamente a fine.',
    tradeoff: 'Buffer più grandi riducono chiamate I/O ma consumano memoria; per testo scegli sempre un charset deterministico.',
    commonError: 'Convertire byte e String usando il charset predefinito della macchina e ottenere risultati diversi tra sistemi.', source: api('API java.io — Java SE 25', 'java.base/java/io/package-summary.html'),
    lab: { method: 'countUtf8Bytes', title: 'Misura testo UTF-8', signature: 'static int countUtf8Bytes(String text)', scenario: 'Un protocollo limita il payload in byte, non nel numero di char Java.', goal: 'Restituisci la lunghezza della codifica UTF-8 e rifiuta null.', main: 'System.out.println(countUtf8Bytes("caffè"));', stub: 'static int countUtf8Bytes(String text) {\n        // TODO: codifica con charset esplicito\n        return 0;\n    }', cases: [{ input: '"Java"', output: '4', purpose: 'ASCII.' }, { input: '"è"', output: '2', purpose: 'Più byte per carattere.' }, { input: 'null', output: 'IllegalArgumentException', purpose: 'Input assente.' }], reflection: 'Perché length() non misura il payload UTF-8?', challenge: 'Confronta char, code point e byte per una emoji.' },
  }),
  createLesson({
    number: '23', title: 'Date, tempo e fusi orari', area: 'Robustezza e libreria standard', level: 'Intermedio', minimumJdk: '17', keywords: ['Instant', 'LocalDate', 'ZoneId', 'Duration'],
    definition: 'Instant identifica un punto sulla linea temporale; i tipi Local non hanno fuso, mentre ZonedDateTime combina data-ora e regole di zona.',
    mentalModel: 'Conserva gli eventi globali come Instant e applica il fuso soltanto per regole civili o presentazione.',
    analogy: 'L’istante è la stessa videoconferenza; l’orario sul calendario cambia in base alla città del partecipante.',
    syntax: 'Instant now = Instant.now();\nZonedDateTime rome = now.atZone(ZoneId.of("Europe/Rome"));',
    example: 'LocalDate date = LocalDate.of(2026, 2, 28);\nSystem.out.println(date.plusDays(1));',
    edgeRule: 'Durante cambi d’ora legale un orario locale può non esistere o essere ambiguo; usa le regole di ZoneId.',
    tradeoff: 'LocalDate è ideale per compleanni e scadenze civili; Instant per timestamp ordinabili tra sistemi.',
    commonError: 'Usare LocalDateTime come timestamp globale e perdere il fuso necessario a interpretarlo.', source: api('API java.time — Java SE 25', 'java.base/java/time/package-summary.html'),
    lab: { method: 'hoursBetween', title: 'Durata tra eventi', signature: 'static long hoursBetween(java.time.Instant start, java.time.Instant end)', scenario: 'Un monitor deve misurare ore trascorse tra due eventi globali.', goal: 'Restituisci le ore complete con Duration, rifiutando null e intervalli negativi.', main: 'var start = java.time.Instant.parse("2026-01-01T00:00:00Z");\nSystem.out.println(hoursBetween(start, start.plusSeconds(9000)));', stub: 'static long hoursBetween(java.time.Instant start, java.time.Instant end) {\n        // TODO: valida ordine e usa Duration\n        return 0;\n    }', cases: [{ input: '0 → 9000 secondi', output: '2', purpose: 'Ore complete.' }, { input: 'stesso istante', output: '0', purpose: 'Durata zero.' }, { input: 'end prima di start / null', output: 'IllegalArgumentException', purpose: 'Intervallo non valido.' }], reflection: 'Perché Duration è più adatta di sottrarre campi hour?', challenge: 'Mostra gli stessi istanti in due ZoneId senza cambiare la durata.' },
  }),
  createLesson({
    number: '24', title: 'Regex, Unicode e testo affidabile', area: 'Robustezza e libreria standard', level: 'Intermedio', minimumJdk: '17', keywords: ['Pattern', 'Matcher', 'Unicode', 'code point'],
    definition: 'Una regex descrive un linguaggio di stringhe; Unicode distingue unità char UTF-16 e code point, che non coincidono sempre.',
    mentalModel: 'Pattern compila la regola, Matcher conserva lo stato della ricerca. Per testo Unicode ragiona sul simbolo richiesto, non automaticamente sul char.',
    analogy: 'Una regex è una sagoma che riconosce forme; il fatto che una forma occupi due tasselli UTF-16 non la rende due simboli umani.',
    syntax: 'Pattern code = Pattern.compile("[A-Z]{2}-\\d{4}");\nboolean valid = code.matcher("IT-2026").matches();',
    example: 'String text = "A😀B";\nSystem.out.println(text.length()); // 4\nSystem.out.println(text.codePointCount(0, text.length())); // 3',
    edgeRule: 'matches verifica l’intera stringa, find cerca una sottosequenza; confonderli cambia il contratto.',
    tradeoff: 'Regex è concisa per grammatiche locali; un parser esplicito è più leggibile per strutture annidate o regole complesse.',
    commonError: 'Dimenticare il doppio livello di escape tra letterale Java e sintassi della regex.', source: api('API Pattern — Java SE 25', 'java.base/java/util/regex/Pattern.html'),
    lab: { method: 'isProductCode', title: 'Valida un codice prodotto', signature: 'static boolean isProductCode(String value)', scenario: 'Un catalogo accetta codici con due lettere maiuscole, trattino e quattro cifre ASCII.', goal: 'Compila un Pattern condiviso e valida l’intera stringa; null deve restituire false.', main: 'System.out.println(isProductCode("IT-2026"));', stub: 'static boolean isProductCode(String value) {\n        // TODO: usa matches sul contratto completo\n        return false;\n    }', cases: [{ input: '"IT-2026"', output: 'true', purpose: 'Formato esatto.' }, { input: '"XIT-2026Y"', output: 'false', purpose: 'Sottostringa non sufficiente.' }, { input: 'null / "it-2026"', output: 'false', purpose: 'Assenza e maiuscole.' }], reflection: 'Quale differenza osservabile esiste tra matches e find?', challenge: 'Accetta lettere Unicode maiuscole motivando la nuova regola.' },
  }),
  createLesson({
    number: '25', title: 'Numeri, BigDecimal e casualità', area: 'Robustezza e libreria standard', level: 'Intermedio', minimumJdk: '17', keywords: ['BigDecimal', 'rounding', 'RandomGenerator', 'precisione'],
    definition: 'BigDecimal rappresenta numeri decimali con precisione arbitraria e scala esplicita; la casualità richiede distinguere simulazione, test e sicurezza.',
    mentalModel: 'Valore non significa rappresentazione: 0.1 non è esatto in binario double, mentre BigDecimal costruito da stringa conserva le cifre decimali.',
    analogy: 'Un registro contabile conserva centesimi esatti; una misura scientifica può invece tollerare un’approssimazione binaria.',
    syntax: 'BigDecimal price = new BigDecimal("19.90");\nBigDecimal total = price.multiply(BigDecimal.valueOf(3));',
    example: 'System.out.println(0.1 + 0.2);\nSystem.out.println(new BigDecimal("0.1").add(new BigDecimal("0.2")));',
    edgeRule: 'La divisione BigDecimal non terminante richiede precisione o modalità di arrotondamento esplicita.',
    tradeoff: 'BigDecimal è corretto per denaro ma più verboso e costoso di double; double resta adatto a molte misure approssimate.',
    commonError: 'Costruire BigDecimal da un letterale double e incorporarne l’approssimazione binaria.', source: api('API BigDecimal — Java SE 25', 'java.base/java/math/BigDecimal.html'),
    lab: { method: 'applyVat', title: 'Calcola un totale monetario', signature: 'static java.math.BigDecimal applyVat(java.math.BigDecimal net, java.math.BigDecimal rate)', scenario: 'Una fattura deve applicare una percentuale e arrotondare a due decimali con regola dichiarata.', goal: 'Calcola net × (1 + rate), rifiuta valori null o negativi e usa HALF_UP a due decimali.', main: 'System.out.println(applyVat(new java.math.BigDecimal("19.90"), new java.math.BigDecimal("0.22")));', stub: 'static java.math.BigDecimal applyVat(java.math.BigDecimal net, java.math.BigDecimal rate) {\n        // TODO: valida, calcola e arrotonda\n        return java.math.BigDecimal.ZERO;\n    }', cases: [{ input: '19.90, 0.22', output: '24.28', purpose: 'Arrotondamento monetario.' }, { input: '0, 0.22', output: '0.00', purpose: 'Zero valido.' }, { input: 'negativo / null', output: 'IllegalArgumentException', purpose: 'Dominio non valido.' }], reflection: 'Perché la modalità di arrotondamento fa parte del contratto?', challenge: 'Distribuisci uno sconto su più righe conservando il totale esatto.' },
  }),
  createLesson({
    number: '26', title: 'Generics e sicurezza dei tipi', area: 'Astrazioni e stile funzionale', level: 'Intermedio', minimumJdk: '17', keywords: ['generics', 'type parameter', 'erasure', 'invarianza'],
    definition: 'Un parametro di tipo descrive una famiglia di tipi mantenendo controlli statici e riducendo cast; l’erasure preserva compatibilità del runtime.',
    mentalModel: 'T è una relazione tra posizioni di input e output, non un contenitore universale. List<Integer> non è sottotipo di List<Number>.',
    analogy: 'Una scatola etichettata T collega ciò che entra e ciò che esce; cambiare etichetta rompe la garanzia sul contenuto.',
    syntax: 'static <T> T first(List<T> values) { return values.get(0); }',
    example: 'String name = first(List.of("Ada", "Linus"));\nInteger number = first(List.of(1, 2));',
    edgeRule: 'Non puoi creare new T() o new T[] direttamente perché il tipo concreto non è disponibile in quel punto dopo erasure.',
    tradeoff: 'I generics spostano errori al compilatore; riflessione e array reificati seguono regole diverse da comprendere.',
    commonError: 'Usare raw type e perdere la relazione tra elemento inserito e valore estratto.', source: jls('JLS §4.5 — Parameterized Types', 'jls-4.html#jls-4.5'),
    lab: { method: 'last', title: 'Ultimo elemento tipato', signature: 'static <T> T last(java.util.List<T> values)', scenario: 'Una libreria deve restituire l’ultimo elemento conservando il suo tipo statico.', goal: 'Implementa last rifiutando null e lista vuota senza cast.', main: 'String value = last(java.util.List.of("A", "B"));\nSystem.out.println(value);', stub: 'static <T> T last(java.util.List<T> values) {\n        // TODO: valida e usa la relazione di tipo\n        return null;\n    }', cases: [{ input: '[A,B]', output: '"B" come String', purpose: 'Inferenza del tipo.' }, { input: '[1]', output: '1 come Integer', purpose: 'Tipo differente.' }, { input: '[] / null', output: 'IllegalArgumentException', purpose: 'Nessun risultato valido.' }], reflection: 'Quale garanzia andrebbe persa restituendo Object?', challenge: 'Restituisci Optional<T> e rivaluta il contratto per lista vuota.' },
  }),
  createLesson({
    number: '27', title: 'Bound, wildcard e principio PECS', area: 'Astrazioni e stile funzionale', level: 'Intermedio', minimumJdk: '17', keywords: ['wildcard', 'extends', 'super', 'PECS'],
    definition: 'Una wildcard descrive una famiglia di tipi parametrizzati: extends è adatta a leggere produttori, super a scrivere consumatori.',
    mentalModel: 'Con ? extends Number conosci un limite superiore ma non il tipo esatto da inserire; con ? super Integer puoi inserire Integer ma leggere solo Object.',
    analogy: 'Da un distributore sai che escono bevande, ma non puoi ricaricarlo con un tipo arbitrario; un contenitore autorizzato per bevande accetta invece la categoria prevista.',
    syntax: 'static double sum(List<? extends Number> values) { /* legge */ }\nstatic void addZeros(List<? super Integer> out) { out.add(0); }',
    example: 'List<Integer> ints = new ArrayList<>();\nList<? super Integer> sink = ints;\nsink.add(7);',
    edgeRule: 'List<?> permette lettura sicura come Object ma non inserimenti diversi da null, perché il tipo elemento preciso è ignoto.',
    tradeoff: 'Wildcard aumenta flessibilità delle API; un parametro di tipo nominato è migliore quando più posizioni devono condividere lo stesso tipo.',
    commonError: 'Usare extends su una destinazione e poi tentare di aggiungere elementi.', source: jls('JLS §4.5.1 — Type Arguments', 'jls-4.html#jls-4.5.1'),
    lab: { method: 'copyNonNull', title: 'Copia tra collezioni compatibili', signature: 'static <T> void copyNonNull(java.util.List<? extends T> source, java.util.List<? super T> destination)', scenario: 'Un adattatore deve copiare elementi non null da una sorgente specializzata a una destinazione più generale.', goal: 'Applica PECS, rifiuta collezioni null e conserva ordine e contenuto precedente della destinazione.', main: 'var out = new java.util.ArrayList<Number>();\ncopyNonNull(java.util.List.of(1, 2), out);\nSystem.out.println(out);', stub: 'static <T> void copyNonNull(java.util.List<? extends T> source, java.util.List<? super T> destination) {\n        // TODO: leggi dal producer e scrivi nel consumer\n    }', cases: [{ input: 'List<Integer> → List<Number>', output: 'elementi copiati', purpose: 'Varianza sicura.' }, { input: 'sorgente vuota', output: 'destinazione invariata', purpose: 'Zero iterazioni.' }, { input: 'source/destination null', output: 'IllegalArgumentException', purpose: 'Dipendenza assente.' }], reflection: 'Perché source non può essere List<T> senza perdere flessibilità?', challenge: 'Aggiungi un Predicate<? super T> per filtrare la copia.' },
  }),
  createLesson({
    number: '28', title: 'Annotazioni e reflection', area: 'Astrazioni e stile funzionale', level: 'Avanzato', minimumJdk: '17', keywords: ['annotation', 'reflection', 'metadata', 'retention'],
    definition: 'Un’annotazione aggiunge metadati dichiarativi; reflection ispeziona tipi e membri a runtime rispettando accessibilità e retention.',
    mentalModel: 'Il codice annotato non cambia comportamento da solo: serve un compilatore, framework o programma che interpreti il metadato.',
    analogy: 'Un’etichetta “fragile” non sposta la scatola; deve esistere un operatore che legga l’etichetta e agisca.',
    syntax: '@Retention(RetentionPolicy.RUNTIME)\n@interface Label { String value(); }',
    example: '@Label("service") class Worker {}\nLabel label = Worker.class.getAnnotation(Label.class);',
    edgeRule: 'Retention SOURCE e CLASS non garantiscono disponibilità tramite reflection a runtime; scegli la policy in base al consumatore.',
    tradeoff: 'I metadati riducono configurazione ripetitiva, ma reflection indebolisce controlli statici e può rendere il flusso meno evidente.',
    commonError: 'Assumere che un’annotazione personalizzata venga automaticamente validata o eseguita.', source: api('API java.lang.reflect — Java SE 25', 'java.base/java/lang/reflect/package-summary.html'),
    lab: { method: 'labelOf', title: 'Leggi metadati runtime', signature: 'static String labelOf(Class<?> type)', scenario: 'Un registro deve ricavare una label dichiarativa dalle classi e usare il nome semplice come fallback.', goal: 'Crea @Label runtime su TYPE e implementa labelOf rifiutando type null.', main: 'System.out.println(labelOf(Worker.class));', stub: '@java.lang.annotation.Retention(java.lang.annotation.RetentionPolicy.RUNTIME)\n    @java.lang.annotation.Target(java.lang.annotation.ElementType.TYPE)\n    @interface Label { String value(); }\n    @Label("worker") static class Worker {}\n    static String labelOf(Class<?> type) { return ""; }', cases: [{ input: 'Worker annotata', output: '"worker"', purpose: 'Metadato presente.' }, { input: 'Main non annotata', output: '"Main"', purpose: 'Fallback.' }, { input: 'null', output: 'IllegalArgumentException', purpose: 'Tipo assente.' }], reflection: 'Quale componente rende operativa l’annotazione?', challenge: 'Valida che la label non sia blank e discuti quando eseguire il controllo.' },
  }),
  createLesson({
    number: '29', title: 'Lambda e interfacce funzionali', area: 'Astrazioni e stile funzionale', level: 'Intermedio', minimumJdk: '17', keywords: ['lambda', 'functional interface', 'closure', 'method reference'],
    definition: 'Una lambda fornisce il comportamento richiesto dall’unico metodo astratto di un’interfaccia funzionale e può catturare variabili locali effectively final.',
    mentalModel: 'Il contesto determina il tipo target della lambda; parametri e corpo implementano il metodo astratto, mentre i valori catturati appartengono all’ambiente di creazione.',
    analogy: 'Consegni una regola a un algoritmo come consegneresti una funzione di controllo a una macchina già costruita.',
    syntax: 'Predicate<String> nonBlank = value -> value != null && !value.isBlank();',
    example: 'Function<String, Integer> length = String::length;\nSystem.out.println(length.apply("Java"));',
    edgeRule: 'Una variabile locale catturata non può essere riassegnata, perché la lambda cattura il valore logico e può vivere oltre il frame.',
    tradeoff: 'Lambda brevi rendono esplicita una politica; corpi lunghi o con molti effetti collaterali meritano un metodo nominato.',
    commonError: 'Confondere il momento di creazione della lambda con il momento successivo in cui viene invocata.', source: jls('JLS §15.27 — Lambda Expressions', 'jls-15.html#jls-15.27'),
    lab: { method: 'select', title: 'Filtra con una politica', signature: 'static java.util.List<Integer> select(java.util.List<Integer> values, java.util.function.IntPredicate rule)', scenario: 'Un report deve riusare lo stesso algoritmo con criteri di selezione diversi.', goal: 'Restituisci una nuova lista contenente gli elementi accettati dalla regola, rifiutando dipendenze null.', main: 'System.out.println(select(java.util.List.of(1,2,3,4), value -> value % 2 == 0));', stub: 'static java.util.List<Integer> select(java.util.List<Integer> values, java.util.function.IntPredicate rule) {\n        // TODO: applica la policy a ogni elemento\n        return new java.util.ArrayList<>();\n    }', cases: [{ input: '[1,2,3,4], pari', output: '[2,4]', purpose: 'Lambda come strategia.' }, { input: '[], qualsiasi regola', output: '[]', purpose: 'Nessuna invocazione.' }, { input: 'lista/regola null', output: 'IllegalArgumentException', purpose: 'Collaboratore obbligatorio.' }], reflection: 'Perché il metodo non deve conoscere la regola “pari”?', challenge: 'Generalizza select con Predicate<? super T>.' },
  }),
  createLesson({
    number: '30', title: 'Stream: pipeline e valutazione lazy', area: 'Astrazioni e stile funzionale', level: 'Intermedio', minimumJdk: '17', keywords: ['Stream', 'lazy', 'intermediate', 'terminal'],
    definition: 'Uno Stream descrive una pipeline: operazioni intermedie lazy trasformano la sequenza e un’operazione terminale avvia il consumo.',
    mentalModel: 'Immagina ogni elemento attraversare l’intera catena, non collezioni temporanee create dopo ogni operazione.',
    analogy: 'Una linea di montaggio applica più stazioni allo stesso pezzo prima di prendere il successivo.',
    syntax: 'long count = values.stream().filter(v -> v > 0).distinct().count();',
    example: 'var result = java.util.stream.Stream.of(" a ", "", "b")\n    .map(String::trim).filter(s -> !s.isEmpty()).toList();',
    edgeRule: 'Uno Stream è consumabile una sola volta e non possiede dati: la sorgente e le operazioni devono restare valide fino al terminale.',
    tradeoff: 'Le pipeline esprimono trasformazioni dichiarative; cicli espliciti sono spesso più chiari con stato complesso, più uscite o debug passo-passo.',
    commonError: 'Definire una pipeline senza operazione terminale e aspettarsi che map o filter vengano eseguiti.', source: api('API Stream — Java SE 25', 'java.base/java/util/stream/Stream.html'),
    lab: { method: 'normalizedLongWords', title: 'Costruisci una pipeline', signature: 'static java.util.List<String> normalizedLongWords(java.util.List<String> words)', scenario: 'Un indicizzatore deve normalizzare parole, eliminare vuoti e duplicati e tenere quelle lunghe almeno quattro caratteri.', goal: 'Crea una pipeline senza mutare l’input e restituisci una lista non modificabile.', main: 'System.out.println(normalizedLongWords(java.util.List.of(" Java ", "java", "JVM", "code")));', stub: 'static java.util.List<String> normalizedLongWords(java.util.List<String> words) {\n        // TODO: map, filter, distinct e toList\n        return java.util.List.of();\n    }', cases: [{ input: '[" Java ","java","JVM","code"]', output: '[java,code]', purpose: 'Pipeline completa.' }, { input: '[]', output: '[]', purpose: 'Sorgente vuota.' }, { input: 'lista/elemento null', output: 'IllegalArgumentException', purpose: 'Precondizioni.' }], reflection: 'In quale ordine metteresti map, filter e distinct per rendere corretto il risultato?', challenge: 'Misura quante volte viene invocato il predicato con limit(1).' },
  }),
  createLesson({
    number: '31', title: 'Collector, Optional e composizione', area: 'Astrazioni e stile funzionale', level: 'Intermedio', minimumJdk: '17', keywords: ['Collector', 'Optional', 'reduce', 'composizione'],
    definition: 'Un Collector accumula elementi in un risultato strutturato; Optional rappresenta esplicitamente zero o un valore senza usare null come sentinella.',
    mentalModel: 'Collector separa supplier, accumulazione, combinazione e finisher; Optional obbliga il chiamante a scegliere cosa fare in assenza.',
    analogy: 'Il collector è un processo di raccolta con contenitore e regole di fusione; Optional è una busta che può essere vuota ma resta un oggetto valido.',
    syntax: 'Map<Integer, List<String>> byLength = words.stream().collect(Collectors.groupingBy(String::length));',
    example: 'Optional<String> longest = words.stream().max(Comparator.comparingInt(String::length));',
    edgeRule: 'Non usare Optional.get senza verificare; map trasforma un valore presente, orElseGet calcola il fallback soltanto se serve.',
    tradeoff: 'Optional è adatto ai risultati di metodo; campi e parametri Optional spesso complicano modelli e serializzazione.',
    commonError: 'Usare orElse con una funzione costosa credendo che venga valutata soltanto quando Optional è vuoto.', source: api('API Collectors — Java SE 25', 'java.base/java/util/stream/Collectors.html'),
    lab: { method: 'mostFrequent', title: 'Riduci a un risultato opzionale', signature: 'static java.util.Optional<String> mostFrequent(java.util.List<String> words)', scenario: 'Un analizzatore deve trovare la parola più frequente senza inventare un valore quando l’elenco è vuoto.', goal: 'Raggruppa e conta, poi restituisci Optional con pareggio risolto alfabeticamente; rifiuta null.', main: 'System.out.println(mostFrequent(java.util.List.of("b", "a", "b")));', stub: 'static java.util.Optional<String> mostFrequent(java.util.List<String> words) {\n        // TODO: raccogli frequenze e scegli il massimo\n        return java.util.Optional.empty();\n    }', cases: [{ input: '[b,a,b]', output: 'Optional[b]', purpose: 'Frequenza massima.' }, { input: '[]', output: 'Optional.empty', purpose: 'Assenza esplicita.' }, { input: 'lista/elemento null', output: 'IllegalArgumentException', purpose: 'Input non valido.' }], reflection: 'Perché la lista vuota non dovrebbe produrre una stringa vuota?', challenge: 'Rendi configurabile la regola di pareggio.' },
  }),
  createLesson({
    number: '32', title: 'Thread, race condition e visibilità', area: 'Concorrenza e JVM', level: 'Avanzato', minimumJdk: '17', keywords: ['Thread', 'race condition', 'visibilità', 'interleaving'],
    definition: 'Una race condition rende il risultato dipendente dall’interleaving di operazioni non coordinate su stato condiviso.',
    mentalModel: 'Scomponi ogni operazione composta in lettura, calcolo e scrittura; considera tutte le possibili alternanze tra thread.',
    analogy: 'Due persone leggono lo stesso saldo, aggiungono separatamente e sovrascrivono il risultato dell’altra.',
    syntax: 'Thread first = new Thread(task);\nfirst.start();\nfirst.join();',
    example: 'int current = counter; // lettura\nint next = current + 1; // calcolo\ncounter = next; // scrittura',
    edgeRule: 'start stabilisce happens-before verso il thread avviato e join verso il thread che attende; sleep non è sincronizzazione.',
    tradeoff: 'Stato immutabile o confinato elimina molte race; condividere stato mutabile richiede un protocollo verificabile.',
    commonError: 'Usare volatile su counter++ credendo di rendere atomica la sequenza lettura-modifica-scrittura.', source: jls('JLS §17 — Threads and Locks', 'jls-17.html'),
    lab: { method: 'runWorkers', title: 'Osserva una race', signature: 'static int runWorkers(int workers, int increments) throws InterruptedException', scenario: 'Un contatore condiviso deve registrare lavoro concorrente; prima osservi il difetto, poi lo correggi.', goal: 'Avvia worker, attendili con join e rendi il conteggio deterministico senza affidarti a sleep.', main: 'System.out.println(runWorkers(4, 1000));', stub: 'static int runWorkers(int workers, int increments) throws InterruptedException {\n        // TODO: crea thread, coordina incremento e join\n        return 0;\n    }', cases: [{ input: '4 × 1000', output: '4000', purpose: 'Aggiornamenti concorrenti.' }, { input: '0 worker', output: '0', purpose: 'Nessun lavoro.' }, { input: 'valori negativi', output: 'IllegalArgumentException', purpose: 'Dominio non valido.' }], reflection: 'Mostra un interleaving che perde un incremento.', challenge: 'Confronta synchronized e AtomicInteger misurando senza trarre conclusioni da una sola esecuzione.' },
  }),
  createLesson({
    number: '33', title: 'Monitor, lock e operazioni atomiche', area: 'Concorrenza e JVM', level: 'Avanzato', minimumJdk: '17', keywords: ['synchronized', 'Lock', 'AtomicInteger', 'invariante'],
    definition: 'Un monitor o lock protegge un invariante composto tramite mutua esclusione e visibilità; una classe atomica protegge operazioni specifiche su un singolo valore.',
    mentalModel: 'Definisci quale lock possiede ogni stato condiviso e mantieni tutte le letture e scritture dell’invariante sotto lo stesso protocollo.',
    analogy: 'Una sola chiave protegge una stanza con più registri correlati; chi entra deve aggiornare l’insieme prima di restituirla.',
    syntax: 'synchronized (lock) {\n    if (balance >= amount) balance -= amount;\n}',
    example: 'AtomicInteger counter = new AtomicInteger();\nint value = counter.incrementAndGet();',
    edgeRule: 'Acquisire lock in ordini differenti può creare deadlock; documenta un ordine globale quando ne servono più di uno.',
    tradeoff: 'Atomiche sono ottime per transizioni semplici; un lock rende indivisibili invarianti tra più campi ma serializza la sezione critica.',
    commonError: 'Proteggere la scrittura con un lock e leggere lo stesso campo senza lo stesso protocollo.', source: api('API java.util.concurrent.atomic', 'java.base/java/util/concurrent/atomic/package-summary.html'),
    lab: { method: 'SafeWallet', title: 'Proteggi un invariante concorrente', signature: 'static final class SafeWallet', scenario: 'Più thread tentano prelievi senza permettere al saldo di diventare negativo.', goal: 'Rendi deposit, withdraw e balance thread-safe usando un unico protocollo di sincronizzazione.', main: 'SafeWallet wallet = new SafeWallet(100);\nSystem.out.println(wallet.withdraw(40));', stub: 'static final class SafeWallet {\n        private int balance;\n        SafeWallet(int balance){ this.balance=balance; }\n        boolean withdraw(int amount){ return false; }\n        void deposit(int amount){}\n        int balance(){ return balance; }\n    }', cases: [{ input: 'saldo100, prelievo40', output: 'true / 60', purpose: 'Caso normale.' }, { input: 'due prelievi80 concorrenti', output: 'uno solo riesce', purpose: 'Invariante composto.' }, { input: 'importo non positivo', output: 'IllegalArgumentException', purpose: 'Contratto.' }], reflection: 'Perché controllare e sottrarre devono essere un’unica sezione critica?', challenge: 'Implementa con ReentrantLock e garantisci unlock in finally.' },
  }),
  createLesson({
    number: '34', title: 'ExecutorService e Future', area: 'Concorrenza e JVM', level: 'Avanzato', minimumJdk: '17', keywords: ['ExecutorService', 'Future', 'Callable', 'shutdown'],
    definition: 'ExecutorService separa invio dei task dalla gestione dei thread; Future rappresenta un risultato che può completarsi, fallire o essere annullato.',
    mentalModel: 'Il chiamante consegna unità di lavoro a un esecutore con ciclo di vita esplicito e osserva ogni esito tramite Future.',
    analogy: 'Un ufficio smista pratiche agli operatori e rilascia ricevute con cui attendere o annullare il risultato.',
    syntax: 'try (ExecutorService pool = Executors.newFixedThreadPool(2)) {\n    Future<Integer> result = pool.submit(() -> 42);\n}',
    example: 'Future<String> future = pool.submit(() -> "ok");\nSystem.out.println(future.get());',
    edgeRule: 'Future.get può bloccare e rilancia ExecutionException; il ciclo di vita dell’esecutore deve sempre terminare.',
    tradeoff: 'Pool limitati controllano risorse CPU o dipendenze scarse; dimensionarli senza conoscere il carico produce code o contesa.',
    commonError: 'Creare un nuovo pool per ogni task e non chiuderlo.', source: api('API ExecutorService — Java SE 25', 'java.base/java/util/concurrent/ExecutorService.html'),
    lab: { method: 'parallelSquares', title: 'Raccogli risultati concorrenti', signature: 'static java.util.List<Integer> parallelSquares(java.util.List<Integer> values) throws Exception', scenario: 'Un calcolo indipendente per elemento deve essere eseguito da un pool limitato conservando l’ordine dei risultati.', goal: 'Invia Callable, conserva i Future in ordine, raccogli risultati e chiudi sempre l’esecutore.', main: 'System.out.println(parallelSquares(java.util.List.of(2,3,4)));', stub: 'static java.util.List<Integer> parallelSquares(java.util.List<Integer> values) throws Exception {\n        // TODO: executor, submit, get e chiusura\n        return java.util.List.of();\n    }', cases: [{ input: '[2,3,4]', output: '[4,9,16]', purpose: 'Ordine conservato.' }, { input: '[]', output: '[]', purpose: 'Nessun task.' }, { input: 'lista null', output: 'IllegalArgumentException', purpose: 'Input assente.' }], reflection: 'Perché la lista dei Future è distinta dalla lista dei risultati?', challenge: 'Aggiungi timeout e politica di annullamento degli altri task.' },
  }),
  createLesson({
    number: '35', title: 'CompletableFuture e pipeline asincrone', area: 'Concorrenza e JVM', level: 'Avanzato', minimumJdk: '17', keywords: ['CompletableFuture', 'thenApply', 'thenCompose', 'exceptionally'],
    definition: 'CompletableFuture rappresenta uno stadio completabile e permette di comporre trasformazioni, dipendenze asincrone e politiche d’errore.',
    mentalModel: 'Disegna un grafo: thenApply trasforma un valore, thenCompose appiattisce uno stadio che produce un altro stadio, thenCombine unisce rami indipendenti.',
    analogy: 'Una ricevuta di lavorazione può attivare automaticamente il passaggio successivo senza che qualcuno resti fermo allo sportello.',
    syntax: 'CompletableFuture<Integer> length = future.thenApply(String::length);',
    example: 'CompletableFuture.completedFuture("java")\n    .thenApply(String::toUpperCase)\n    .thenAccept(System.out::println);',
    edgeRule: 'join incapsula il fallimento in CompletionException; gestire l’errore troppo presto può nascondere la causa o trasformarlo in successo.',
    tradeoff: 'La composizione non bloccante è utile per dipendenze asincrone; per flussi lineari bloccanti i virtual thread sono spesso più leggibili.',
    commonError: 'Usare thenApply con una funzione che restituisce CompletableFuture e ottenere uno stadio annidato.', source: api('API CompletableFuture — Java SE 25', 'java.base/java/util/concurrent/CompletableFuture.html'),
    lab: { method: 'combineLengths', title: 'Combina due risultati', signature: 'static java.util.concurrent.CompletableFuture<Integer> combineLengths(String first, String second)', scenario: 'Due valori vengono elaborati indipendentemente e il chiamante vuole la somma delle lunghezze.', goal: 'Crea due stadi asincroni, combinali senza get intermedio e rifiuta input null prima di avviarli.', main: 'System.out.println(combineLengths("Java", "JVM").join());', stub: 'static java.util.concurrent.CompletableFuture<Integer> combineLengths(String first, String second) {\n        // TODO: due rami e thenCombine\n        return java.util.concurrent.CompletableFuture.completedFuture(0);\n    }', cases: [{ input: '"Java","JVM"', output: '7', purpose: 'Rami indipendenti.' }, { input: '"",""', output: '0', purpose: 'Valori vuoti.' }, { input: 'un valore null', output: 'IllegalArgumentException', purpose: 'Errore sincrono di contratto.' }], reflection: 'Perché thenCombine esprime meglio la dipendenza rispetto a due join consecutivi?', challenge: 'Propaga un errore da un ramo e osserva la CompletionException.' },
  }),
  createLesson({
    number: '36', title: 'Virtual thread e carichi bloccanti', area: 'Concorrenza e JVM', level: 'Avanzato', minimumJdk: '21', keywords: ['virtual thread', 'blocking I/O', 'throughput', 'Semaphore'],
    definition: 'Un virtual thread è un Thread leggero gestito dal JDK, adatto a molti task concorrenti che trascorrono tempo bloccati su I/O.',
    mentalModel: 'Il virtual thread si smonta dal carrier durante molte operazioni bloccanti; non rende più veloce il lavoro CPU-bound e non va messo in pool.',
    analogy: 'Molti clienti possono lasciare temporaneamente lo sportello mentre attendono un documento, liberando l’operatore per altri.',
    syntax: 'try (var executor = Executors.newVirtualThreadPerTaskExecutor()) {\n    executor.submit(task);\n}',
    example: 'Thread thread = Thread.startVirtualThread(() -> System.out.println(Thread.currentThread().isVirtual()));',
    edgeRule: 'Per limitare accesso a una risorsa scarsa usa Semaphore o un pool della risorsa, non un pool di virtual thread.',
    tradeoff: 'Virtual thread semplificano codice bloccante ad alto throughput; parallelismo CPU resta limitato dai core disponibili.',
    commonError: 'Creare un fixed thread pool di virtual thread o usarne milioni per calcoli CPU-bound aspettandosi accelerazione.', source: { label: 'JEP 444 — Virtual Threads', url: 'https://openjdk.org/jeps/444' },
    lab: { method: 'runVirtualTasks', title: 'Esegui task bloccanti leggeri', signature: 'static int runVirtualTasks(int count) throws Exception', scenario: 'Un simulatore deve avviare molti task indipendenti che attendono brevemente e restituiscono un valore.', goal: 'Usa un virtual-thread-per-task executor, raccogli tutti i Future e restituisci la somma.', main: 'System.out.println(runVirtualTasks(20));', stub: 'static int runVirtualTasks(int count) throws Exception {\n        // TODO: un virtual thread per task, nessun pool fisso\n        return 0;\n    }', cases: [{ input: '20 task che restituiscono 1', output: '20', purpose: 'Molti task.' }, { input: '0', output: '0', purpose: 'Nessun task.' }, { input: 'count negativo', output: 'IllegalArgumentException', purpose: 'Dominio non valido.' }], reflection: 'Perché aumentare i thread non accelera un algoritmo CPU-bound?', challenge: 'Aggiungi un Semaphore con massimo tre task nella sezione simulata come risorsa scarsa.' },
  }),
  createLesson({
    number: '37', title: 'Collezioni concorrenti e Java Memory Model', area: 'Concorrenza e JVM', level: 'Avanzato', minimumJdk: '17', keywords: ['ConcurrentHashMap', 'happens-before', 'visibility', 'atomic compute'],
    definition: 'Le collezioni concorrenti offrono operazioni thread-safe con garanzie di visibilità; sequenze di più operazioni richiedono comunque una transizione atomica esplicita.',
    mentalModel: 'Ragiona in relazioni happens-before, non in “tempo sufficiente”. Una singola operazione compute può proteggere la decisione legata alla chiave.',
    analogy: 'Un registro condiviso permette aggiornamenti coordinati per casella, ma leggere e poi scrivere con due moduli separati riapre una finestra di conflitto.',
    syntax: 'counts.compute(key, (k, old) -> old == null ? 1 : old + 1);',
    example: 'ConcurrentHashMap<String, LongAdder> counts = new ConcurrentHashMap<>();\ncounts.computeIfAbsent("java", k -> new LongAdder()).increment();',
    edgeRule: 'Gli iteratori sono weakly consistent: non lanciano necessariamente ConcurrentModificationException e possono osservare una vista in evoluzione.',
    tradeoff: 'ConcurrentHashMap scala meglio di un lock globale per chiavi indipendenti, ma non rende atomiche operazioni tra chiavi diverse.',
    commonError: 'Scrivere if (!map.containsKey(k)) map.put(k, v) credendo che la sequenza sia atomica.', source: api('API ConcurrentHashMap — Java SE 25', 'java.base/java/util/concurrent/ConcurrentHashMap.html'),
    lab: { method: 'countConcurrently', title: 'Frequenze concorrenti', signature: 'static java.util.Map<String, Integer> countConcurrently(java.util.List<String> words) throws Exception', scenario: 'Più task aggiornano le frequenze delle parole in una mappa condivisa.', goal: 'Usa ConcurrentHashMap.compute o merge e attendi tutti i task prima di restituire una copia.', main: 'System.out.println(countConcurrently(java.util.List.of("a","b","a")));', stub: 'static java.util.Map<String, Integer> countConcurrently(java.util.List<String> words) throws Exception {\n        // TODO: aggiornamenti atomici per chiave e attesa\n        return java.util.Map.of();\n    }', cases: [{ input: '[a,b,a]', output: '{a=2,b=1}', purpose: 'Aggiornamenti stessa chiave.' }, { input: '[]', output: '{}', purpose: 'Nessun task.' }, { input: 'lista/elemento null', output: 'IllegalArgumentException', purpose: 'Contratto.' }], reflection: 'Perché containsKey seguito da put non è equivalente a computeIfAbsent?', challenge: 'Usa LongAdder e discuti quando la somma è una fotografia coerente.' },
  }),
];
