import { createLesson } from './course-factory';

const api = (label: string, path: string) => ({
  label,
  url: `https://docs.oracle.com/en/java/javase/25/docs/api/${path}`,
});

export const lessons38to52 = [
  createLesson({
    number: '38', title: 'Package, moduli e JAR', area: 'Ingegneria Java', level: 'Intermedio', minimumJdk: '17', keywords: ['package', 'module-info.java', 'JAR'],
    definition: 'Package, moduli e archivi JAR separano gli spazi dei nomi, dichiarano dipendenze leggibili e distribuiscono classi e risorse come un artefatto coerente.',
    mentalModel: 'Un package organizza i nomi, un modulo stabilisce il confine pubblico e le dipendenze, un JAR è il contenitore fisico: sono tre responsabilità diverse.',
    analogy: 'Il package è l’indirizzo di una stanza, il modulo decide quali porte sono pubbliche e il JAR è l’edificio consegnato.',
    syntax: 'module com.example.app {\n    requires java.net.http;\n    exports com.example.api;\n}',
    example: 'String entry = "com/example/api/Service.class";\nSystem.out.println(entry);',
    edgeRule: 'Il percorso nel JAR deve corrispondere al nome qualificato; esportare un package non rende automaticamente pubblici i suoi tipi non public.',
    tradeoff: 'I moduli rendono espliciti confini e dipendenze, ma introducono configurazione che un piccolo programma a singolo file può non richiedere.',
    commonError: 'Confondere classpath e module path oppure collocare una classe in una directory che non corrisponde alla dichiarazione package.',
    source: { label: 'Java Platform Module System — Java SE 25', url: 'https://docs.oracle.com/javase/specs/jls/se25/html/jls-7.html' },
    lab: { method: 'jarEntry', title: 'Deriva il percorso di una classe nel JAR', signature: 'static String jarEntry(String packageName, String className)', scenario: 'Un tool di build deve convertire il nome di package e classe nel percorso della relativa entry compilata.', goal: 'Valida i nomi e restituisci il percorso con slash e suffisso .class.', main: 'System.out.println(jarEntry("com.example.api", "Service"));', stub: 'static String jarEntry(String packageName, String className) {\n        // TODO: valida e trasforma com.example.api + Service\n        return "";\n    }', cases: [{ input: 'com.example.api, Service', output: 'com/example/api/Service.class', purpose: 'Nome qualificato.' }, { input: 'package vuoto, Main', output: 'Main.class', purpose: 'Package unnamed.' }, { input: 'classe vuota o null', output: 'IllegalArgumentException', purpose: 'Contratto.' }], reflection: 'Quale problema risolve exports che un semplice package non risolve?', challenge: 'Genera anche il comando javac --module-path senza eseguirlo.' },
  }),
  createLesson({
    number: '39', title: 'Test automatici e sviluppo guidato dai test', area: 'Ingegneria Java', level: 'Intermedio', minimumJdk: '17', keywords: ['test', 'asserzione', 'TDD'],
    definition: 'Un test automatico prepara uno scenario, esegue un’unità e confronta il risultato osservato con un esito atteso ripetibile.',
    mentalModel: 'Ogni test è un piccolo esperimento controllato: Arrange costruisce lo stato, Act produce un solo effetto, Assert verifica una proprietà significativa.',
    analogy: 'Come una prova di laboratorio, un test è utile se il campione è noto, la procedura è ripetibile e il criterio di successo è deciso prima.',
    syntax: 'int actual = sum(2, 3);\nif (actual != 5) throw new AssertionError("atteso 5");',
    example: 'record Case(int a, int b, int expected) {}\nvar c = new Case(2, 3, 5);\nassert c.a() + c.b() == c.expected();',
    edgeRule: 'I test devono essere deterministici e indipendenti: ordine, orario, rete e stato globale non possono cambiare casualmente l’esito.',
    tradeoff: 'TDD rende esplicito il contratto e favorisce design testabile, ma test troppo accoppiati all’implementazione rallentano ogni refactoring.',
    commonError: 'Scrivere un test senza asserzioni, catturare qualunque eccezione o verificare dettagli privati invece del comportamento pubblico.',
    source: { label: 'JUnit 5 User Guide', url: 'https://junit.org/junit5/docs/current/user-guide/' },
    lab: { method: 'runCases', title: 'Costruisci un micro test runner', signature: 'static int runCases(java.util.List<int[]> cases)', scenario: 'Prima di introdurre JUnit vuoi capire meccanicamente che cosa fa un runner di test.', goal: 'Ogni array contiene a, b e somma attesa: esegui tutti i casi e restituisci quanti passano.', main: 'System.out.println(runCases(java.util.List.of(new int[]{2,3,5}, new int[]{-1,1,0})));', stub: 'static int runCases(java.util.List<int[]> cases) {\n        // TODO: arrange, act e assert per ogni caso\n        return 0;\n    }', cases: [{ input: '[[2,3,5],[-1,1,0]]', output: '2', purpose: 'Due successi.' }, { input: '[[2,2,5]]', output: '0', purpose: 'Fallimento osservabile.' }, { input: 'array non lungo 3', output: 'IllegalArgumentException', purpose: 'Fixture invalida.' }], reflection: 'Perché un test che dipende dall’ordine di esecuzione è fragile?', challenge: 'Trasforma i casi in test parametrizzati JUnit 5 in un progetto Maven separato.' },
  }),
  createLesson({
    number: '40', title: 'Maven, Gradle e dipendenze riproducibili', area: 'Ingegneria Java', level: 'Intermedio', minimumJdk: '17', keywords: ['Maven', 'Gradle', 'versione bloccata'],
    definition: 'Un build tool descrive sorgenti, dipendenze, test e artefatti in modo che la stessa revisione possa produrre lo stesso risultato su macchine diverse.',
    mentalModel: 'Il build è un grafo: i task dipendono da altri task e le librerie da coordinate immutabili. Wrapper e lock file fissano tool e risoluzione.',
    analogy: 'Una ricetta riproducibile indica ingredienti con quantità e versione, non “usa la farina più recente disponibile”.',
    syntax: '<dependency>\n  <groupId>org.junit.jupiter</groupId>\n  <artifactId>junit-jupiter</artifactId>\n  <version>5.13.4</version>\n</dependency>',
    example: 'String coordinate = "org.example:core:1.4.2";\nSystem.out.println(coordinate.split(":")[2]);',
    edgeRule: 'Versioni dinamiche e repository non affidabili rendono il build variabile; il wrapper va versionato e la cache non sostituisce il lock.',
    tradeoff: 'Maven privilegia convenzioni e un modello dichiarativo; Gradle offre maggiore programmabilità, con più libertà e più superficie da governare.',
    commonError: 'Usare latest o intervalli aperti, non versionare il wrapper oppure dichiarare dipendenze transitive come se fossero garantite.',
    source: { label: 'Maven — Introduction to the Dependency Mechanism', url: 'https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html' },
    lab: { method: 'isPinned', title: 'Valida coordinate riproducibili', signature: 'static boolean isPinned(String coordinate)', scenario: 'Una pipeline rifiuta dipendenze prive di una versione esatta.', goal: 'Accetta soltanto coordinate group:artifact:version con versione numerica esplicita e senza +, latest o intervalli.', main: 'System.out.println(isPinned("org.example:core:1.4.2"));', stub: 'static boolean isPinned(String coordinate) {\n        // TODO: valida tre segmenti e una versione esatta\n        return false;\n    }', cases: [{ input: 'org.example:core:1.4.2', output: 'true', purpose: 'Versione fissata.' }, { input: 'org.example:core:latest', output: 'false', purpose: 'Versione dinamica.' }, { input: 'null o formato incompleto', output: 'false', purpose: 'Input invalido.' }], reflection: 'Che differenza c’è tra cache, wrapper e lock delle dipendenze?', challenge: 'Aggiungi un controllo per prerelease e una policy esplicita.' },
  }),
  createLesson({
    number: '41', title: 'Logging, diagnostica e osservabilità', area: 'Ingegneria Java', level: 'Intermedio', minimumJdk: '17', keywords: ['Logger', 'livello', 'correlation id'],
    definition: 'Il logging registra eventi strutturati e contestualizzati; diagnostica e osservabilità permettono di ricostruire il comportamento senza esporre dati sensibili.',
    mentalModel: 'Un log utile risponde a che cosa è accaduto, dove e per quale richiesta, mantenendo separati messaggio, livello e contesto.',
    analogy: 'Il giornale di bordo non sostituisce il timone: documenta decisioni e anomalie con coordinate sufficienti per ricostruirle.',
    syntax: 'System.getLogger("course").log(System.Logger.Level.INFO, "lesson={0}", 41);',
    example: 'System.Logger log = System.getLogger("app");\nlog.log(System.Logger.Level.WARNING, "retry requestId={0}", "r-42");',
    edgeRule: 'Password, token, chiavi e dati personali non devono apparire nei log; messaggi ad alta cardinalità richiedono una policy di conservazione.',
    tradeoff: 'Più contesto accelera la diagnosi, ma aumenta volume, costo e rischio privacy; livelli e campionamento devono riflettere l’uso operativo.',
    commonError: 'Concatenare segreti o stack trace indiscriminati, usare ERROR per eventi normali o registrare messaggi senza identificatore di richiesta.',
    source: api('API System.Logger — Java SE 25', 'java.base/java/lang/System.Logger.html'),
    lab: { method: 'sanitizeLog', title: 'Rendi sicuro un evento di log', signature: 'static String sanitizeLog(String message)', scenario: 'Un servizio riceve messaggi che possono contenere token nel formato token=valore.', goal: 'Oscura il valore del token, normalizza i ritorni a capo e limita il messaggio a 160 caratteri.', main: 'System.out.println(sanitizeLog("login token=abc123\\nok"));', stub: 'static String sanitizeLog(String message) {\n        // TODO: neutralizza injection e segreti\n        return "";\n    }', cases: [{ input: 'login token=abc123', output: 'login token=[REDACTED]', purpose: 'Segreto oscurato.' }, { input: 'a\\nb', output: 'a b', purpose: 'Una sola riga.' }, { input: 'null', output: 'IllegalArgumentException', purpose: 'Contratto.' }], reflection: 'Quale contesto serve davvero per correlare un errore senza identificare una persona?', challenge: 'Produci un record LogEvent e serializzalo in un formato strutturato.' },
  }),
  createLesson({
    number: '42', title: 'JDBC, transazioni e consistenza', area: 'Ingegneria Java', level: 'Avanzato', minimumJdk: '17', keywords: ['JDBC', 'transazione', 'PreparedStatement'],
    definition: 'JDBC espone connessioni, statement e result set; una transazione raggruppa modifiche che devono riuscire o fallire come un’unica unità.',
    mentalModel: 'Una transazione attraversa stati espliciti: inizio, operazioni, commit; qualunque errore prima del commit conduce al rollback.',
    analogy: 'Un trasferimento bancario non è “tolgo e poi forse aggiungo”: le due scritture appartengono allo stesso confine atomico.',
    syntax: 'connection.setAutoCommit(false);\ntry { /* statement */ connection.commit(); }\ncatch (SQLException e) { connection.rollback(); throw e; }',
    example: 'try (var ps = connection.prepareStatement("select name from users where id = ?")) {\n    ps.setLong(1, id);\n}',
    edgeRule: 'PreparedStatement parametrizza valori, non nomi di tabella; connection, statement e result set devono essere chiusi anche in caso di eccezione.',
    tradeoff: 'Transazioni più ampie semplificano la consistenza applicativa, ma trattengono risorse e contese più a lungo.',
    commonError: 'Costruire SQL concatenando input, dimenticare il rollback o lasciare autoCommit attivo durante un’operazione composta.',
    source: { label: 'JDBC Basics — Oracle', url: 'https://docs.oracle.com/javase/tutorial/jdbc/basics/index.html' },
    lab: { method: 'transactionPlan', title: 'Modella il confine transazionale', signature: 'static java.util.List<String> transactionPlan(boolean secondWriteSucceeds)', scenario: 'Prima di collegare un database devi rendere osservabile l’ordine delle operazioni di un trasferimento.', goal: 'Restituisci BEGIN, le due WRITE e COMMIT; se la seconda fallisce termina con ROLLBACK e non con COMMIT.', main: 'System.out.println(transactionPlan(false));', stub: 'static java.util.List<String> transactionPlan(boolean secondWriteSucceeds) {\n        // TODO: modella il percorso commit/rollback\n        return java.util.List.of();\n    }', cases: [{ input: 'true', output: '[BEGIN, WRITE_DEBIT, WRITE_CREDIT, COMMIT]', purpose: 'Percorso riuscito.' }, { input: 'false', output: '[BEGIN, WRITE_DEBIT, WRITE_CREDIT_FAILED, ROLLBACK]', purpose: 'Percorso atomico.' }, { input: 'ogni percorso', output: 'esattamente un finale', purpose: 'Né commit e rollback insieme né nessuno.' }], reflection: 'Perché il rollback deve stare nello stesso livello che possiede la connessione?', challenge: 'Implementa la stessa macchina a stati con una Connection finta e verifica le chiamate.' },
  }),
  createLesson({
    number: '43', title: 'HTTP Client, protocolli e JSON', area: 'Ingegneria Java', level: 'Avanzato', minimumJdk: '17', keywords: ['HttpClient', 'URI', 'status code'],
    definition: 'Un client HTTP costruisce richieste, applica timeout e interpreta status, header e body come parti distinte del protocollo.',
    mentalModel: 'Trasporto riuscito non significa operazione riuscita: prima arriva una risposta HTTP, poi l’applicazione decide cosa significhino stato e payload.',
    analogy: 'Il corriere può consegnare correttamente una busta che contiene un rifiuto: consegna e contenuto hanno esiti differenti.',
    syntax: 'HttpRequest request = HttpRequest.newBuilder(uri)\n    .timeout(Duration.ofSeconds(5)).GET().build();',
    example: 'HttpClient client = HttpClient.newHttpClient();\n// HttpResponse<String> response = client.send(request, BodyHandlers.ofString());',
    edgeRule: 'Imposta timeout, limita la dimensione dei body e valida redirect e URI; il parsing JSON richiede una libreria o un modello esplicito.',
    tradeoff: 'L’API sincrona è lineare e adatta a virtual thread; sendAsync compone pipeline, ma propaga errori in modo meno immediato.',
    commonError: 'Considerare ogni risposta 2xx, ignorare charset e timeout oppure inserire token direttamente nell’URL.',
    source: api('API HttpClient — Java SE 25', 'java.net.http/java/net/http/HttpClient.html'),
    lab: { method: 'buildRequest', title: 'Costruisci una richiesta difensiva', signature: 'static java.net.http.HttpRequest buildRequest(java.net.URI uri, String requestId)', scenario: 'Un client deve preparare GET HTTPS ripetibili senza effettuare rete durante l’esercizio.', goal: 'Accetta solo HTTPS, imposta timeout di 5 secondi e header Accept e X-Request-Id.', main: 'System.out.println(buildRequest(java.net.URI.create("https://example.com/api"), "r-42").headers().map());', stub: 'static java.net.http.HttpRequest buildRequest(java.net.URI uri, String requestId) {\n        // TODO: schema, timeout e header\n        return null;\n    }', cases: [{ input: 'https URI, r-42', output: 'GET con due header e timeout 5s', purpose: 'Richiesta valida.' }, { input: 'http URI', output: 'IllegalArgumentException', purpose: 'Trasporto non cifrato.' }, { input: 'requestId vuoto', output: 'IllegalArgumentException', purpose: 'Correlazione obbligatoria.' }], reflection: 'Perché status code e body vanno validati separatamente?', challenge: 'Aggiungi una policy controllata per redirect e una dimensione massima del body.' },
  }),
  createLesson({
    number: '44', title: 'Secure coding e gestione della configurazione', area: 'Ingegneria Java', level: 'Avanzato', minimumJdk: '17', keywords: ['validazione', 'segreto', 'least privilege'],
    definition: 'Il secure coding riduce la superficie d’attacco validando ai confini, proteggendo i segreti e concedendo soltanto le capacità necessarie.',
    mentalModel: 'Ogni dato esterno è non attendibile finché non supera una policy; ogni capacità è negata finché non viene concessa esplicitamente.',
    analogy: 'Un controllo accessi efficace verifica identità e permesso alla porta corretta, non appende la chiave alla maniglia.',
    syntax: 'String token = System.getenv("APP_TOKEN");\nif (token == null || token.isBlank()) throw new IllegalStateException("config mancante");',
    example: 'Path base = Path.of("data").toAbsolutePath().normalize();\nPath target = base.resolve(userName).normalize();\nif (!target.startsWith(base)) throw new SecurityException();',
    edgeRule: 'La validazione avviene dopo decodifica e normalizzazione; i segreti non entrano in codice, log, URL o repository.',
    tradeoff: 'Una allowlist è più restrittiva e prevedibile di una denylist, ma richiede manutenzione quando si aggiungono casi legittimi.',
    commonError: 'Fidarsi dell’estensione di un file, validare prima della normalizzazione o conservare una chiave API in application.properties versionato.',
    source: { label: 'OWASP Java Security Cheat Sheet', url: 'https://cheatsheetseries.owasp.org/cheatsheets/Java_Security_Cheat_Sheet.html' },
    lab: { method: 'safeResolve', title: 'Blocca il path traversal', signature: 'static java.nio.file.Path safeResolve(java.nio.file.Path base, String userPath)', scenario: 'Un servizio locale deve leggere un file scelto dall’utente senza uscire dalla cartella autorizzata.', goal: 'Normalizza base e target, rifiuta path assoluti e ogni risultato che non inizi con la base.', main: 'System.out.println(safeResolve(java.nio.file.Path.of("data"), "notes/java.txt"));', stub: 'static java.nio.file.Path safeResolve(java.nio.file.Path base, String userPath) {\n        // TODO: normalizza e applica una allowlist di directory\n        return null;\n    }', cases: [{ input: 'data, notes/java.txt', output: 'percorso dentro data', purpose: 'Percorso valido.' }, { input: 'data, ../secret.txt', output: 'SecurityException', purpose: 'Traversal.' }, { input: 'base o path null', output: 'IllegalArgumentException', purpose: 'Contratto.' }], reflection: 'Perché cercare la stringa ".." non è una difesa sufficiente?', challenge: 'Aggiungi una allowlist di estensioni dopo aver risolto il percorso.' },
  }),
  createLesson({
    number: '45', title: 'Memoria JVM e garbage collection', area: 'Java moderno e prestazioni', level: 'Avanzato', minimumJdk: '17', keywords: ['heap', 'garbage collector', 'retention'],
    definition: 'La JVM gestisce memoria per oggetti, stack e metadati; il garbage collector recupera oggetti non più raggiungibili, non quelli ancora trattenuti per errore.',
    mentalModel: 'Parti dai GC root e segui i riferimenti: un oggetto è vivo se esiste un cammino raggiungibile, indipendentemente dalla sua utilità applicativa.',
    analogy: 'Il servizio di raccolta può rimuovere scatole abbandonate, non quelle ancora legate con una corda al magazzino.',
    syntax: 'try (InputStream in = Files.newInputStream(path)) {\n    // la risorsa nativa ha un ciclo di vita esplicito\n}',
    example: 'var cache = new java.util.LinkedHashMap<String, byte[]>();\n// senza limite, riferimenti ancora raggiungibili impediscono il recupero',
    edgeRule: 'Il GC non chiude tempestivamente file o socket e non corregge cache senza limiti; le risorse esterne richiedono ownership esplicita.',
    tradeoff: 'Heap più grande riduce alcuni cicli di raccolta ma può aumentare footprint e durata delle pause; serve misurare il carico reale.',
    commonError: 'Chiamare System.gc come soluzione, confondere memory leak con oggetto non raccolto subito o trattenere listener e cache per sempre.',
    source: { label: 'Java HotSpot VM Garbage Collection Tuning Guide', url: 'https://docs.oracle.com/en/java/javase/25/gctuning/' },
    lab: { method: 'boundedCache', title: 'Progetta una cache con limite', signature: 'static java.util.Map<String, String> boundedCache(java.util.List<String> values, int maxSize)', scenario: 'Una cache locale deve mantenere soltanto gli ultimi valori senza crescere indefinitamente.', goal: 'Restituisci una LinkedHashMap che non supera maxSize e rimuove l’entry inserita meno recentemente.', main: 'System.out.println(boundedCache(java.util.List.of("a","b","c","d"), 2));', stub: 'static java.util.Map<String, String> boundedCache(java.util.List<String> values, int maxSize) {\n        // TODO: applica ownership e limite espliciti\n        return java.util.Map.of();\n    }', cases: [{ input: '[a,b,c,d], 2', output: '{c=c,d=d}', purpose: 'Eviction.' }, { input: '[], 3', output: '{}', purpose: 'Nessuna retention.' }, { input: 'maxSize <= 0', output: 'IllegalArgumentException', purpose: 'Capacità invalida.' }], reflection: 'Perché una cache illimitata è un memory leak anche se tutti i riferimenti sono formalmente validi?', challenge: 'Implementa ordine access-based e confrontalo con insertion-based.' },
  }),
  createLesson({
    number: '46', title: 'Profilazione, JFR e misurazione', area: 'Java moderno e prestazioni', level: 'Avanzato', minimumJdk: '17', keywords: ['JFR', 'profilazione', 'benchmark'],
    definition: 'La profilazione raccoglie evidenze su CPU, allocazioni, lock e I/O; Java Flight Recorder osserva la JVM con eventi temporali a basso overhead.',
    mentalModel: 'Ottimizzare è un ciclo: formula un’ipotesi, misura una baseline, cambia una variabile, misura di nuovo e conserva soltanto il miglioramento verificato.',
    analogy: 'Un medico non prescrive sulla base del rumore percepito: raccoglie segni, formula una diagnosi e controlla l’effetto della cura.',
    syntax: 'var recording = new jdk.jfr.Recording();\nrecording.start();\n// workload\nrecording.stop();',
    example: 'long start = System.nanoTime();\nwork.run();\nlong elapsed = System.nanoTime() - start;',
    edgeRule: 'Una singola misura include warm-up, compilazione JIT e rumore; microbenchmark seri richiedono un harness come JMH.',
    tradeoff: 'JFR offre una vista ampia con overhead contenuto; profiler più invasivi possono dare dettaglio maggiore alterando maggiormente il sistema.',
    commonError: 'Ottimizzare senza baseline, usare currentTimeMillis per microbenchmark o dedurre la causa da un solo campione.',
    source: { label: 'Java Flight Recorder Runtime Guide', url: 'https://docs.oracle.com/en/java/javase/25/jfapi/' },
    lab: { method: 'medianNanos', title: 'Riduci il rumore di una misura', signature: 'static long medianNanos(Runnable task, int repetitions)', scenario: 'Vuoi costruire un esercizio preliminare alla profilazione senza fingere che sia un benchmark scientifico.', goal: 'Esegui warm-up, misura più ripetizioni con nanoTime e restituisci la mediana.', main: 'System.out.println(medianNanos(() -> Math.sqrt(42), 9) >= 0);', stub: 'static long medianNanos(Runnable task, int repetitions) {\n        // TODO: warm-up, misure, ordinamento e mediana\n        return 0L;\n    }', cases: [{ input: 'task rapido, 9', output: 'valore >= 0', purpose: 'Misura valida.' }, { input: 'task incrementa contatore, 5', output: 'eseguito warm-up + 5 volte', purpose: 'Protocollo.' }, { input: 'ripetizioni pari o <= 0', output: 'IllegalArgumentException', purpose: 'Mediana univoca.' }], reflection: 'Perché questo metodo non sostituisce JMH?', challenge: 'Registra un evento JFR personalizzato intorno al task e ispezionalo con jfr print.' },
  }),
  createLesson({
    number: '47', title: 'Java 21: pattern e collezioni sequenziate', area: 'Java moderno e prestazioni', level: 'Avanzato', minimumJdk: '21', keywords: ['record pattern', 'switch pattern', 'SequencedCollection'],
    definition: 'Java 21 rende finali pattern matching per switch, record pattern e collezioni sequenziate, riducendo cast e convenzioni per primo, ultimo e vista inversa.',
    mentalModel: 'Un pattern verifica forma e tipo mentre estrae componenti; una collezione sequenziata dichiara formalmente un incontro ordinato da due estremità.',
    analogy: 'Un controllo doganale può riconoscere il tipo di collo e aprirne direttamente gli scomparti dichiarati, senza una seconda procedura di cast.',
    syntax: 'return switch (shape) {\n    case Circle(double r) -> Math.PI * r * r;\n    case Rectangle(double w, double h) -> w * h;\n};',
    example: 'var values = new java.util.ArrayList<>(java.util.List.of("a", "b", "c"));\nSystem.out.println(values.reversed());',
    edgeRule: 'Uno switch su gerarchia sealed deve essere esaustivo; reversed restituisce una vista collegata, non necessariamente una copia.',
    tradeoff: 'I pattern rendono il dispatch sui dati conciso ed esaustivo, ma non sostituiscono il polimorfismo quando il comportamento appartiene naturalmente al tipo.',
    commonError: 'Aggiungere default a uno switch sealed nascondendo nuovi sottotipi o modificare una vista reversed credendola indipendente.',
    source: { label: 'JEP 441 — Pattern Matching for switch', url: 'https://openjdk.org/jeps/441' },
    lab: { method: 'rotateLastToFirst', title: 'Usa una collezione sequenziata', signature: 'static <T> java.util.List<T> rotateLastToFirst(java.util.List<T> input)', scenario: 'Una coda editoriale deve portare l’ultimo elemento in testa conservando l’ordine degli altri.', goal: 'Crea una copia, usa le operazioni first/last di Java 21 e non modificare l’input.', main: 'System.out.println(rotateLastToFirst(java.util.List.of("a","b","c")));', stub: 'static <T> java.util.List<T> rotateLastToFirst(java.util.List<T> input) {\n        // TODO: getLast/removeLast/addFirst su una copia\n        return java.util.List.of();\n    }', cases: [{ input: '[a,b,c]', output: '[c,a,b]', purpose: 'Rotazione.' }, { input: '[]', output: '[]', purpose: 'Confine vuoto.' }, { input: 'null', output: 'IllegalArgumentException', purpose: 'Contratto.' }], reflection: 'Quando reversed è preferibile a creare una copia invertita?', challenge: 'Modella Shape come gerarchia sealed e calcola l’area con record pattern.' },
  }),
  createLesson({
    number: '48', title: 'Java 25 e governo delle feature preview', area: 'Java moderno e prestazioni', level: 'Avanzato', minimumJdk: '25', keywords: ['Java 25', 'preview feature', 'release cadence'],
    definition: 'Java 25 è una release LTS che include feature finali e preview; una feature preview richiede opt-in, può cambiare e non va confusa con un contratto stabile.',
    mentalModel: 'Classifica ogni feature per stato e versione: final è supportata normalmente, preview richiede flag coordinati in compilazione ed esecuzione, incubator vive in moduli separati.',
    analogy: 'Una preview è un laboratorio aperto al pubblico: utile per valutare il progetto, ma la planimetria può ancora cambiare.',
    syntax: 'javac --release 25 --enable-preview Main.java\njava --enable-preview Main',
    example: '// Java 25 finale: module import declarations\n// import module java.base;\n// Le preview vanno sempre verificate nei JEP della release.',
    edgeRule: 'Codice compilato con preview deve essere eseguito con preview della stessa release; aggiornare il JDK richiede ricompilazione e revisione della feature.',
    tradeoff: 'Provare una preview anticipa apprendimento e feedback, ma aumenta rischio di migrazione; isolarla dietro un confine riduce il costo.',
    commonError: 'Presentare Structured Concurrency di Java 25 come definitiva, abilitare preview in produzione senza policy o omettere --enable-preview a runtime.',
    source: { label: 'JEP 511 — Module Import Declarations', url: 'https://openjdk.org/jeps/8344700' },
    lab: { method: 'featurePolicy', title: 'Applica una policy alle feature', signature: 'static String featurePolicy(String status, boolean production)', scenario: 'Un team deve decidere se una feature final, preview o incubator può entrare nel ramo di produzione.', goal: 'Restituisci ALLOW per final, ISOLATE per preview non production e REJECT negli altri casi; valida lo stato.', main: 'System.out.println(featurePolicy("preview", false));', stub: 'static String featurePolicy(String status, boolean production) {\n        // TODO: policy esplicita, senza dipendere da una preview\n        return "";\n    }', cases: [{ input: 'final, true', output: 'ALLOW', purpose: 'Contratto stabile.' }, { input: 'preview, false', output: 'ISOLATE', purpose: 'Esperimento controllato.' }, { input: 'preview, true / incubator', output: 'REJECT', purpose: 'Protezione produzione.' }], reflection: 'Quali prove servono prima di adottare una preview?', challenge: 'Crea una matrice di compatibilità per compile, test e runtime con --enable-preview.' },
  }),
  createLesson({
    number: '49', title: 'Capstone: biblioteca a oggetti', area: 'Progetti conclusivi', level: 'Progetto', minimumJdk: '21', keywords: ['domain model', 'invariante', 'repository'],
    definition: 'Un modello di dominio traduce regole reali in oggetti con responsabilità, invarianti e transizioni esplicite, separando logica e persistenza.',
    mentalModel: 'Identifica entità, oggetti valore, eventi e confini transazionali prima delle classi; ogni metodo di dominio deve preservare gli invarianti.',
    analogy: 'Una biblioteca non è una tabella di libri: prestiti, copie, utenti e scadenze hanno identità e regole differenti.',
    syntax: 'record BookId(String value) {}\nsealed interface LoanResult permits Loaned, Rejected {}',
    example: 'if (activeLoans >= limit) return new Rejected("limite raggiunto");\nreturn new Loaned(copyId, dueDate);',
    edgeRule: 'La stessa copia non può essere prestata due volte e un’operazione fallita non deve lasciare stato parzialmente modificato.',
    tradeoff: 'Un dominio ricco protegge le regole vicino ai dati; troppe astrazioni per un requisito piccolo aumentano il costo cognitivo.',
    commonError: 'Creare sole classi anemiche con setter pubblici, usare String per ogni identità o far dipendere il dominio dal database.',
    source: { label: 'Java Tutorials — Object-Oriented Programming Concepts', url: 'https://docs.oracle.com/javase/tutorial/java/concepts/' },
    lab: { method: 'loan', title: 'Implementa il nucleo della biblioteca', signature: 'static String loan(java.util.Map<String, String> loans, String copyId, String userId)', scenario: 'La biblioteca registra quale utente possiede ogni copia e deve rifiutare doppi prestiti.', goal: 'Valida le identità, registra atomicamente il prestito e restituisci LOANED o ALREADY_LOANED senza sovrascrivere.', main: 'var loans = new java.util.HashMap<String,String>();\nSystem.out.println(loan(loans, "copy-1", "user-7"));', stub: 'static String loan(java.util.Map<String, String> loans, String copyId, String userId) {\n        // TODO: invariante e transizione atomica\n        return "";\n    }', cases: [{ input: 'mappa vuota, copy-1, user-7', output: 'LOANED e nuova entry', purpose: 'Prestito valido.' }, { input: 'copy-1 già presente', output: 'ALREADY_LOANED e valore invariato', purpose: 'Invariante.' }, { input: 'id vuoto/null', output: 'IllegalArgumentException', purpose: 'Oggetto valore valido.' }], reflection: 'Quale classe dovrebbe possedere la regola sul numero massimo di prestiti?', challenge: 'Estendi il progetto con record identificativi, Repository in memoria e test di accettazione.' },
  }),
  createLesson({
    number: '50', title: 'Capstone: analizzatore di file', area: 'Progetti conclusivi', level: 'Progetto', minimumJdk: '21', keywords: ['Files', 'Stream', 'report'],
    definition: 'Un analizzatore di file affidabile separa acquisizione, parsing, aggregazione e presentazione, mantenendo limiti di memoria ed errori contestualizzati.',
    mentalModel: 'Trasforma una sorgente potenzialmente grande in una pipeline: ogni riga diventa dato validato, poi statistica; il report è un risultato distinto.',
    analogy: 'Una catena di smistamento controlla ogni pacco, lo classifica e aggiorna il registro senza accumulare l’intero magazzino sul nastro.',
    syntax: 'try (var lines = Files.lines(path, StandardCharsets.UTF_8)) {\n    return lines.filter(p).collect(collector);\n}',
    example: 'record Stats(long lines, long words, long characters) {}',
    edgeRule: 'Files.lines mantiene una risorsa aperta e il conteggio di caratteri Java non equivale sempre a code point o grafemi Unicode.',
    tradeoff: 'Lo streaming limita memoria e parte subito; più passaggi sullo stesso dato possono però richiedere un collector combinato più complesso.',
    commonError: 'Usare readAllLines su file senza limite, perdere charset ed eccezione di riga o dimenticare di chiudere lo stream.',
    source: api('API Files — Java SE 25', 'java.base/java/nio/file/Files.html'),
    lab: { method: 'analyze', title: 'Genera statistiche in un passaggio', signature: 'static Stats analyze(java.util.List<String> lines)', scenario: 'Il laboratorio usa righe in memoria per progettare la parte pura prima di collegare Files.lines.', goal: 'Calcola righe, parole non vuote e code point in un solo attraversamento.', imports: 'record Stats(long lines, long words, long codePoints) {}', main: 'System.out.println(analyze(java.util.List.of("Java è", "chiaro")));', stub: 'static Stats analyze(java.util.List<String> lines) {\n        // TODO: validazione e singolo passaggio\n        return new Stats(0, 0, 0);\n    }', cases: [{ input: '["Java è","chiaro"]', output: 'Stats[lines=2, words=3, codePoints=12]', purpose: 'Conteggi combinati.' }, { input: '[]', output: 'tutti zero', purpose: 'File vuoto.' }, { input: 'lista o riga null', output: 'IllegalArgumentException', purpose: 'Parsing affidabile.' }], reflection: 'Come collegheresti Files.lines mantenendo analyze testabile?', challenge: 'Leggi un Path UTF-8, produci top 10 parole e salva un report atomico.' },
  }),
  createLesson({
    number: '51', title: 'Capstone: aggregatore concorrente', area: 'Progetti conclusivi', level: 'Progetto', minimumJdk: '21', keywords: ['virtual thread', 'timeout', 'partial failure'],
    definition: 'Un aggregatore concorrente avvia richieste indipendenti, impone deadline, raccoglie risultati e rende esplicita la politica per fallimenti parziali.',
    mentalModel: 'Ogni task ha ownership e ciclo di vita; il chiamante possiede deadline, cancellazione e decisione finale, non soltanto la creazione dei thread.',
    analogy: 'Un coordinatore invia più corrieri ma chiude la raccolta a un orario preciso e registra consegne mancanti invece di attendere per sempre.',
    syntax: 'try (var executor = Executors.newVirtualThreadPerTaskExecutor()) {\n    var future = executor.submit(source);\n    return future.get(2, TimeUnit.SECONDS);\n}',
    example: 'record Result<T>(T value, Throwable error) {\n    boolean succeeded() { return error == null; }\n}',
    edgeRule: 'Timeout e cancellazione devono propagarsi; un fallimento parziale non va né ignorato né trasformato automaticamente in fallimento totale.',
    tradeoff: 'Virtual thread mantengono uno stile sequenziale leggibile per I/O bloccante; la concorrenza resta soggetta a limiti delle risorse esterne.',
    commonError: 'Creare task senza deadline, perdere InterruptedException o aggiornare una ArrayList condivisa da più thread.',
    source: { label: 'JEP 444 — Virtual Threads', url: 'https://openjdk.org/jeps/444' },
    lab: { method: 'aggregate', title: 'Raccogli task indipendenti', signature: 'static int aggregate(java.util.List<java.util.concurrent.Callable<Integer>> tasks) throws Exception', scenario: 'Più sorgenti restituiscono conteggi; il risultato finale è la somma delle sorgenti riuscite.', goal: 'Esegui ogni Callable su virtual thread, attendi i Future e somma; valida input e preserva interruzione.', main: 'System.out.println(aggregate(java.util.List.of(() -> 2, () -> 3)));', stub: 'static int aggregate(java.util.List<java.util.concurrent.Callable<Integer>> tasks) throws Exception {\n        // TODO: ownership executor, Future e somma\n        return 0;\n    }', cases: [{ input: '[() -> 2, () -> 3]', output: '5', purpose: 'Aggregazione.' }, { input: '[]', output: '0', purpose: 'Nessun task.' }, { input: 'task null o lista null', output: 'IllegalArgumentException', purpose: 'Contratto.' }], reflection: 'Dove collocheresti deadline e politica di fallimento parziale?', challenge: 'Aggiungi timeout per task, risultato tipizzato e Semaphore per la risorsa scarsa.' },
  }),
  createLesson({
    number: '52', title: 'Capstone finale: applicazione stratificata', area: 'Progetti conclusivi', level: 'Progetto', minimumJdk: '25', keywords: ['architettura', 'dependency inversion', 'acceptance test'],
    definition: 'Un’applicazione stratificata separa dominio, casi d’uso, adapter e infrastruttura affinché le regole dipendano da contratti stabili e siano verificabili senza servizi reali.',
    mentalModel: 'Le dipendenze puntano verso il dominio: l’esterno traduce HTTP, file o database in porte; il caso d’uso orchestra senza conoscere il framework.',
    analogy: 'Una presa standard separa l’apparecchio dalla centrale elettrica: entrambi rispettano un contratto e possono cambiare indipendentemente.',
    syntax: 'interface TaskRepository { java.util.Optional<Task> find(String id); void save(Task task); }',
    example: 'final class CompleteTask {\n    private final TaskRepository repository;\n    CompleteTask(TaskRepository repository) { this.repository = repository; }\n}',
    edgeRule: 'Una transazione applicativa deve avere un confine chiaro; mapping, validazione e I/O non devono infiltrarsi nell’entità di dominio.',
    tradeoff: 'Le porte rendono test e sostituzioni semplici; per un programma minuscolo troppe interfacce possono essere cerimonia senza beneficio.',
    commonError: 'Far dipendere il dominio dal driver JDBC, usare DTO come entità o introdurre un’interfaccia per ogni classe senza un confine reale.',
    source: { label: 'Java Language Specification — Java SE 25', url: 'https://docs.oracle.com/javase/specs/jls/se25/html/index.html' },
    lab: { method: 'complete', title: 'Orchestra un caso d’uso', signature: 'static String complete(java.util.Map<String, Boolean> repository, String id)', scenario: 'Il capstone finale usa una mappa come adapter in memoria per concentrarsi su contratto e transizione del caso d’uso.', goal: 'Valida id, restituisci NOT_FOUND se assente, ALREADY_DONE se già completo e COMPLETED dopo la sola transizione valida.', main: 'var repo = new java.util.HashMap<String,Boolean>();\nrepo.put("task-1", false);\nSystem.out.println(complete(repo, "task-1"));', stub: 'static String complete(java.util.Map<String, Boolean> repository, String id) {\n        // TODO: caso d’uso, stati e persistenza in memoria\n        return "";\n    }', cases: [{ input: '{task-1=false}, task-1', output: 'COMPLETED e valore true', purpose: 'Happy path.' }, { input: 'id assente / già true', output: 'NOT_FOUND / ALREADY_DONE', purpose: 'Stati distinti.' }, { input: 'repo o id invalido', output: 'IllegalArgumentException', purpose: 'Confine.' }], reflection: 'Quali parti cambierebbero passando dalla mappa a JDBC e quali dovrebbero restare identiche?', challenge: 'Costruisci entità, use case, repository in memoria e su file, CLI adapter e una suite di test di accettazione.' },
  }),
];
