import type { CourseLesson, LabMission, QuizQuestion, TheorySection } from './course-types';

export type { CourseLesson, LabMission, QuizQuestion, TheorySection } from './course-types';

export const lessonOne = {
  number: '01',
  title: 'Stringhe, cicli e casi limite',
  area: 'Fondamenti e problem solving',
  level: 'Fondamenti',
  duration: '60–75 min',
  minimumJdk: '17',
  prerequisites: ['Nessuna esperienza Java richiesta', 'Saper distinguere testo e numero'],
  keywords: ['String', 'char', 'for', 'indice', 'accumulatore', 'StringBuilder'],
  sources: [
    { label: 'JLS §10 — Array e indici', url: 'https://docs.oracle.com/javase/specs/jls/se25/html/jls-10.html' },
    { label: 'JLS §14 — Istruzioni e cicli', url: 'https://docs.oracle.com/javase/specs/jls/se25/html/jls-14.html' },
    { label: 'API String — Java SE 25', url: 'https://docs.oracle.com/en/java/javase/25/docs/api/java.base/java/lang/String.html' },
  ],
  outcome: 'Un analizzatore testuale che conta elementi e gruppi e costruisce una nuova String senza modificare l’originale.',
  objectives: [
    'Spiegare la differenza tra String, char, stringa vuota e riferimento null.',
    'Prevedere le iterazioni di un ciclo indicizzato tracciando indice e accumulatore.',
    'Implementare metodi che rispettano un contratto e gestiscono casi limite.',
    'Confrontare concatenazione iterativa e StringBuilder motivandone i costi.',
  ],
  guidedExercise: [
    'Traccia su carta gli indici e i caratteri della String “A2B7”.',
    'Conta soltanto le cifre mantenendo un risultato parziale.',
    'Ripeti autonomamente con String vuota e un solo carattere.',
  ],
  summary: [
    'Gli indici validi vanno da 0 a length() − 1.',
    'La validazione precede ogni uso del parametro.',
    'Un accumulatore descrive il risultato ottenuto sugli elementi già visitati.',
    'StringBuilder evita di creare una catena di String intermedie.',
  ],
  reviewQuestions: [
    'Come dimostri che un ciclo non supera l’ultimo indice?',
    'Quale invariante descrive il valore del contatore?',
    'Quando useresti una transizione di stato invece di un semplice conteggio?',
  ],
  starterCode: `public class Main {
    public static void main(String[] args) {
        String input = "Educazione";
        int actual = countVowels(input);

        System.out.println("Input: " + input);
        System.out.println("Atteso: 6");
        System.out.println("Ottenuto: " + actual);
    }

    static int countVowels(String text) {
        // TODO: valida null, visita ogni char e conta le vocali.
        return 0;
    }
}`,
  theory: [
    {
      kicker: '01 · Il modello mentale',
      title: 'Un metodo è un piccolo contratto',
      lead: 'Un metodo riceve dei dati, svolge un compito preciso e produce un risultato. La sua firma è la descrizione sintetica di questo accordo.',
      plain: 'Prima di pensare alle istruzioni da scrivere, traduci la firma in una frase italiana. Questo riduce la confusione: sai già quale dato entra, quale risultato deve uscire e quale nome userai per riferirti al dato.',
      analogy: 'Pensa a una macchina per il caffè: inserisci una capsula, scegli il comando e ricevi una bevanda. Parametro, operazione e valore restituito hanno ruoli simili.',
      points: [
        '`public` indica che il metodo può essere richiamato anche da altre classi.',
        '`static` significa che puoi chiamarlo tramite la classe, senza creare prima un oggetto.',
        '`int` è il tipo del risultato promesso: un numero intero.',
        '`String value` è il parametro: il testo ricevuto dal chiamante.',
      ],
      code: 'public static int countDigits(String value)',
      walkthrough: [
        'Il chiamante passa, per esempio, `"A7B20"`.',
        'Dentro il metodo quel testo viene chiamato `value`.',
        'Il metodo esamina il testo e alla fine deve restituire un `int`.',
      ],
      callout: 'Non iniziare dal ciclo: inizia sempre dal contratto.',
      question: 'Come leggeresti a voce `public static String clean(String text)`?',
    },
    {
      kicker: '02 · Riferimenti',
      title: '`null`, stringa vuota e spazi sono tre input diversi',
      lead: 'Una variabile `String` non contiene necessariamente del testo visibile. Può anche non indicare alcun oggetto oppure indicare una sequenza di lunghezza zero.',
      plain: '`null` non è una stringa speciale: è l’assenza di una String. Per questo non puoi chiedergli lunghezza o caratteri. `""`, invece, è un oggetto vero ma vuoto. Uno spazio è un carattere reale, anche se sullo schermo sembra invisibile.',
      analogy: 'Immagina tre scatole: la prima non esiste (`null`), la seconda esiste ma è vuota (`""`), la terza contiene tre fogli bianchi (`"   "`). Sembrano simili, ma non puoi trattarle allo stesso modo.',
      points: [
        '`null`: nessun oggetto; usare `length()` causerebbe una `NullPointerException`.',
        '`""`: String valida con `length()` uguale a 0.',
        '`"   "`: String valida con tre caratteri spazio.',
        'Se il contratto richiede `IllegalArgumentException`, controlla `null` prima di usare il parametro.',
      ],
      code: 'if (name == null) {\n    throw new IllegalArgumentException("name non può essere null");\n}',
      walkthrough: [
        'Prima domanda: il riferimento è `null`?',
        'Se sì, interrompi intenzionalmente il metodo con l’eccezione richiesta.',
        'Solo dopo puoi chiamare in sicurezza `isEmpty()`, `length()` o `charAt(...)`.',
      ],
      callout: 'La validazione va prima dell’elaborazione.',
      question: 'Perché `" "` non può essere considerata una stringa vuota?',
    },
    {
      kicker: '03 · Tipi di testo',
      title: '`String` e `char` rappresentano cose differenti',
      lead: 'Una `String` è una sequenza di zero o più caratteri. Un `char` rappresenta un singolo carattere.',
      plain: 'Quando visiti una parola carattere per carattere, la variabile che contiene l’intera parola resta una `String`; il singolo elemento letto con `charAt` è invece un `char`. Java usa una sintassi diversa per impedire di confonderli.',
      analogy: 'Una String è come un treno; ogni char è un singolo vagone. Puoi studiare il treno intero oppure un vagone alla volta.',
      points: [
        'Le stringhe usano virgolette doppie: `"a"`.',
        'I caratteri usano apici singoli: `\'a\'`.',
        '`String` è immutabile: le sue operazioni non cambiano l’oggetto originale.',
        '`Character.toLowerCase(current)` normalizza un singolo carattere.',
      ],
      code: 'String word = "Casa";\nchar first = word.charAt(0);\nchar normalized = Character.toLowerCase(first);',
      walkthrough: [
        '`word` continua a valere `"Casa"`.',
        '`first` vale `\'C\'`.',
        '`normalized` vale `\'c\'`.',
      ],
      callout: 'Normalizzare il carattere letto non modifica la String originale.',
      question: 'Che tipo hanno rispettivamente `"J"` e `\'J\'`?',
    },
    {
      kicker: '04 · Posizioni',
      title: 'Gli indici iniziano da zero',
      lead: 'Ogni carattere ha una posizione numerica. In Java la prima posizione è 0, non 1.',
      plain: 'La lunghezza indica quanti caratteri esistono, non l’ultimo indice. Se una String ha quattro caratteri, gli indici validi sono 0, 1, 2 e 3. Cercare l’indice 4 significa andare oltre la fine.',
      analogy: 'È come numerare quattro cassetti partendo da zero: 0, 1, 2, 3. Il numero dei cassetti è 4, ma non esiste il cassetto 4.',
      points: [
        '`text.length()` restituisce il numero totale di caratteri.',
        '`text.charAt(index)` legge il carattere nella posizione indicata.',
        'Il primo indice valido è sempre 0, se la String non è vuota.',
        'L’ultimo indice valido è sempre `length() - 1`.',
      ],
      code: 'String text = "Java";\n// indici:     0123\nchar first = text.charAt(0); // J\nchar last  = text.charAt(3); // a',
      walkthrough: [
        '`text.length()` restituisce 4.',
        '`text.charAt(3)` è valido e restituisce l’ultima `a`.',
        '`text.charAt(4)` produce `StringIndexOutOfBoundsException`.',
      ],
      callout: 'Lunghezza 4 significa ultimo indice 3.',
      question: 'Qual è l’ultimo indice valido della String `"codice"`?',
    },
    {
      kicker: '05 · Ripetizione',
      title: 'Il ciclo `for` visita un carattere alla volta',
      lead: 'Un ciclo indicizzato ripete le stesse istruzioni cambiando la posizione osservata.',
      plain: 'Il `for` contiene tre parti: inizializzazione, condizione e aggiornamento. Prima crea `index` con valore 0; prima di ogni giro verifica il confine; dopo ogni giro incrementa l’indice.',
      analogy: 'Immagina un lettore che sposta il dito lungo una parola: parte dalla prima lettera, la legge, avanza di una posizione e si ferma appena non ci sono più lettere.',
      points: [
        '`int index = 0` viene eseguito una sola volta.',
        '`index < text.length()` viene controllato prima di ogni iterazione.',
        '`index++` viene eseguito alla fine di ogni iterazione.',
        '`text.charAt(index)` legge il carattere corrente.',
      ],
      code: 'for (int index = 0; index < text.length(); index++) {\n    char current = text.charAt(index);\n    System.out.println(current);\n}',
      walkthrough: [
        'Con `"OK"`, index 0 legge `\'O\'`.',
        'Poi index diventa 1 e legge `\'K\'`.',
        'Infine index diventa 2: `2 < 2` è falso e il ciclo termina.',
      ],
      callout: 'Usare `<=` tenterebbe un’iterazione di troppo.',
      question: 'Quante volte entra nel ciclo una String di lunghezza zero?',
    },
    {
      kicker: '06 · Tracciamento',
      title: 'Esegui mentalmente il ciclo prima del computer',
      lead: 'Il modo più efficace per capire un ciclo è annotare come cambiano le variabili a ogni iterazione.',
      plain: 'Crea una piccola tabella con indice, carattere corrente e risultato parziale. Questa tecnica si chiama dry run: esecuzione a secco. Ti permette di scoprire errori nei confini senza modificare codice a tentativi.',
      points: [
        'Scrivi il valore iniziale delle variabili.',
        'Valuta la condizione del ciclo come vero o falso.',
        'Esegui mentalmente il corpo usando il carattere corrente.',
        'Aggiorna indice e risultato, poi ripeti.',
      ],
      code: 'String text = "A2B";\n// index | current | è una cifra? | count\n//   0   |   A     | no          | 0\n//   1   |   2     | sì          | 1\n//   2   |   B     | no          | 1',
      walkthrough: [
        'Il contatore parte da 0.',
        'Cambia soltanto quando il carattere soddisfa la condizione.',
        'Dopo l’ultimo carattere il risultato resta 1.',
      ],
      callout: 'Se non sai prevedere la tabella, non sei ancora pronto a scrivere il ciclo.',
      question: 'Nel testo `"3A7"`, quali iterazioni cambiano il contatore delle cifre?',
    },
    {
      kicker: '07 · Risultato parziale',
      title: 'Un accumulatore ricorda ciò che hai già trovato',
      lead: 'Il ciclo osserva un elemento per volta; l’accumulatore conserva il risultato costruito fino a quel momento.',
      plain: 'Per contare, inizializzi normalmente una variabile a zero. Ogni volta che la regola è soddisfatta la incrementi. Alla fine del ciclo la variabile contiene il totale, perché nessun carattere è stato saltato.',
      analogy: 'È come usare un contapersone all’ingresso: parte da zero e fai uno scatto soltanto quando entra una persona valida.',
      points: [
        'L’accumulatore viene dichiarato prima del ciclo.',
        'La condizione decide se aggiornarlo.',
        '`count++` equivale a `count = count + 1`.',
        'Il `return` viene normalmente eseguito dopo aver visitato tutti gli elementi.',
      ],
      code: 'int count = 0;\nfor (...) {\n    if (matchesRule) {\n        count++;\n    }\n}\nreturn count;',
      walkthrough: [
        'Prima del ciclo non hai trovato nulla: count è 0.',
        'Dopo ogni iterazione count descrive ciò che hai esaminato finora.',
        'Questa frase sempre vera è chiamata invariante del ciclo.',
      ],
      callout: 'Aggiorna il contatore soltanto nel punto in cui riconosci una corrispondenza.',
      question: 'Perché dichiarare `count` dentro il ciclo renderebbe impossibile conservare il totale?',
    },
    {
      kicker: '08 · Stato',
      title: 'Contare elementi non è come contare gruppi',
      lead: 'Quando cerchi sequenze consecutive, devi sapere non solo cosa stai leggendo adesso, ma anche in quale stato eri prima.',
      plain: 'Nella sequenza ■■■□□■■ ci sono cinque simboli pieni ma soltanto due gruppi. Un nuovo gruppo va contato solo quando passi dallo stato “fuori” allo stato “dentro”. I simboli successivi appartengono allo stesso gruppo.',
      analogy: 'In un tunnel conti gli ingressi, non ogni metro percorso. Entri una volta, rimani dentro per un tratto ed esci; il tunnel successivo produce un nuovo ingresso.',
      points: [
        'Un booleano può ricordare se sei dentro una sequenza.',
        'Elemento valido mentre sei fuori: nasce un nuovo gruppo.',
        'Elemento valido mentre sei dentro: il gruppo continua.',
        'Separatore: torni nello stato fuori.',
      ],
      code: '// simboli: ■ ■ ■ □ □ ■ ■\n// stato:   IN IN IN OUT OUT IN IN\n// ingressi: 1             2',
      walkthrough: [
        'Il primo ■ provoca la transizione OUT → IN: conta 1.',
        'Gli altri due ■ non cambiano stato.',
        '□ porta lo stato a OUT; il successivo ■ provoca il secondo ingresso.',
      ],
      callout: 'Nell’esercizio userai questo modello per riconoscere l’inizio delle parole.',
      question: 'Quanti gruppi contiene `□□■■□■□□■■■` e in quali posizioni iniziano?',
    },
    {
      kicker: '09 · Costruzione',
      title: '`StringBuilder` costruisce testo senza continue copie',
      lead: 'Una `String` è immutabile: una volta creata non cambia. Le operazioni che sembrano modificarla producono in realtà un nuovo oggetto.',
      plain: 'Concatenare con `+` a ogni iterazione crea molte String intermedie. `StringBuilder` mantiene invece un contenitore modificabile: aggiungi i caratteri e lo converti in String soltanto alla fine.',
      analogy: 'Con `+` fotografi il foglio dopo ogni lettera; con StringBuilder continui a scrivere sullo stesso foglio e fai una sola fotografia alla fine.',
      points: [
        'Crea un solo builder prima del ciclo.',
        '`append(...)` aggiunge un elemento in fondo.',
        '`toString()` produce il risultato finale.',
        'Per cambiare ordine devi scegliere correttamente indice iniziale, direzione e condizione di arresto.',
      ],
      code: 'StringBuilder builder = new StringBuilder();\nbuilder.append(\'C\');\nbuilder.append(\'i\');\nbuilder.append(\'a\');\nString result = builder.toString(); // "Cia"',
      walkthrough: [
        'Il builder nasce vuoto.',
        'Ogni append conserva ciò che era già presente e aggiunge un carattere.',
        'Solo alla fine ottieni una String immutabile.',
      ],
      callout: 'Per invertire non serve una scorciatoia: ragiona sulla direzione degli indici.',
      question: 'Se vuoi leggere una String dalla fine, quale dovrebbe essere il primo indice?',
    },
    {
      kicker: '10 · Progettazione',
      title: 'I casi limite fanno parte dell’algoritmo',
      lead: 'Un’implementazione non è completa finché non sai spiegare cosa accade con input normali, vuoti, minimi e non validi.',
      plain: 'Prima di programmare prepara esempi e risultati attesi. Poi traduci ogni caso in un test. I test non servono soltanto a trovare errori: rendono esplicito il contratto che il metodo deve rispettare.',
      analogy: 'Un ponte non viene collaudato soltanto con il traffico ideale: si controllano anche carico minimo, massimo e condizioni anomale.',
      points: [
        'Caso normale: verifica il comportamento principale.',
        'Caso vuoto: controlla che il ciclo possa non partire.',
        'Un solo carattere: controlla i confini.',
        'Valori ripetuti: controlla stato e transizioni.',
        '`null`: controlla l’eccezione richiesta dal contratto.',
      ],
      code: '// Preparazione → Azione → Verifica\nString input = "A2";\nint result = countDigits(input);\nassertEquals(1, result);',
      walkthrough: [
        'Scegli un input che rappresenta una regola precisa.',
        'Esegui una sola operazione.',
        'Confronta risultato reale e risultato atteso.',
      ],
      callout: 'Un test rosso è informazione: indica quale parte del contratto manca ancora.',
      question: 'Quali cinque categorie di input testeresti prima di considerare completo un metodo sulle String?',
    },
  ] satisfies TheorySection[],
  quiz: [
    { id: 'q1', question: 'Qual è l’ultimo indice valido di una String lunga 6?', options: [{ id: 'a', label: '6' }, { id: 'b', label: '5' }, { id: 'c', label: '7' }], correct: 'b', explanation: 'Gli indici partono da 0: l’ultimo è length − 1, quindi 5.' },
    { id: 'q2', question: 'Quale valore è una String valida lunga zero?', options: [{ id: 'a', label: 'null' }, { id: 'b', label: '" "' }, { id: 'c', label: '""' }], correct: 'c', explanation: '"" è un oggetto String esistente che contiene zero caratteri.' },
    { id: 'q3', question: 'Perché il ciclo usa index < text.length()?', options: [{ id: 'a', label: 'Per non accedere a un indice inesistente' }, { id: 'b', label: 'Per ignorare l’ultimo carattere' }, { id: 'c', label: 'Perché length() parte da zero' }], correct: 'a', explanation: 'L’indice uguale a length() è già oltre l’ultimo carattere.' },
    { id: 'q4', question: 'Quando va incrementato il contatore di gruppi?', options: [{ id: 'a', label: 'Per ogni elemento del gruppo' }, { id: 'b', label: 'Quando si entra in un nuovo gruppo' }, { id: 'c', label: 'Quando termina il ciclo' }], correct: 'b', explanation: 'Il passaggio da “fuori” a “dentro” identifica un nuovo gruppo.' },
    { id: 'q5', question: 'Perché usare StringBuilder in una costruzione iterativa?', options: [{ id: 'a', label: 'String non può contenere spazi' }, { id: 'b', label: 'Per evitare molte String intermedie' }, { id: 'c', label: 'Converte automaticamente in maiuscolo' }], correct: 'b', explanation: 'String è immutabile; StringBuilder accumula senza ricreare il testo a ogni append.' },
    { id: 'q6', question: 'Quando va controllato un parametro null?', options: [{ id: 'a', label: 'Dopo aver chiamato length()' }, { id: 'b', label: 'Prima di usare il parametro' }, { id: 'c', label: 'Soltanto dentro il test' }], correct: 'b', explanation: 'Il controllo deve precedere qualsiasi accesso alla String.' },
    { id: 'q7', question: 'Quante volte entra nel ciclo una String vuota?', options: [{ id: 'a', label: 'Zero' }, { id: 'b', label: 'Una' }, { id: 'c', label: 'Dipende dal carattere' }], correct: 'a', explanation: 'All’inizio 0 < 0 è già falso, quindi il corpo non viene eseguito.' },
  ] satisfies QuizQuestion[],
  lab: [
    {
      method: 'countVowels',
      title: 'Missione A · Conta le vocali',
      signature: 'static int countVowels(String text)',
      scenario: 'Stai costruendo una piccola analisi di leggibilità. Il primo indicatore richiesto è il numero di vocali presenti in un testo, senza distinguere tra lettere maiuscole e minuscole.',
      goal: 'Completa il metodo in modo che restituisca quante volte compaiono a, e, i, o oppure u. Se text è null, il metodo deve interrompersi con IllegalArgumentException.',
      steps: [
        'Prima di scrivere codice, scorri a mano “Educazione” e annota quali caratteri fanno aumentare il contatore.',
        'Gestisci null prima di chiamare qualsiasi metodo su text, poi prepara un contatore iniziale.',
        'Visita la String dall’indice 0 all’ultimo indice valido e normalizza soltanto il carattere corrente.',
        'Incrementa il contatore esclusivamente quando il carattere normalizzato è una delle cinque vocali richieste.',
        'Restituisci il totale e confrontalo con tutti i casi di prova, non soltanto con l’esempio iniziale.',
      ],
      constraints: [
        'Usa un ciclo indicizzato: niente Stream o espressioni regolari, perché qui stai allenando indici e accumulatore.',
        'Non modificare il parametro e non trasformare tutta la String: normalizza il singolo char mentre lo visiti.',
        'Per null lancia IllegalArgumentException; la String vuota è invece un input valido e produce 0.',
      ],
      examples: [
        { input: '"Educazione"', output: '6', purpose: 'Caso normale con una vocale maiuscola.' },
        { input: '"rhythm"', output: '0', purpose: 'Testo senza le cinque vocali richieste.' },
        { input: '""', output: '0', purpose: 'Il ciclo non deve iniziare.' },
        { input: 'null', output: 'IllegalArgumentException', purpose: 'Input non valido da bloccare subito.' },
      ],
      acceptance: [
        'Il file compila senza errori e il metodo restituisce un int.',
        'Maiuscole, minuscole, testo vuoto e testo senza vocali producono il risultato atteso.',
        'null genera esattamente IllegalArgumentException prima del ciclo.',
      ],
      reflection: 'Perché il contatore deve essere dichiarato prima del ciclo? Spiegalo usando il concetto di risultato parziale.',
      challenge: 'Decidi se à, è, ì, ò e ù devono contare. Prima scrivi il nuovo contratto, poi modifica test e implementazione.',
    },
    {
      method: 'countWords',
      title: 'Missione B · Conta le parole',
      signature: 'static int countWords(String text)',
      scenario: 'Lo stesso analizzatore deve ora stimare la lunghezza di una frase contando le parole. Nel contratto di questa missione una parola è una sequenza di caratteri diversi dallo spazio semplice.',
      goal: 'Aggiungi un metodo che conti gli ingressi in una nuova parola. Più spazi consecutivi rappresentano un solo separatore; spazi iniziali o finali non creano parole.',
      steps: [
        'Traccia “  uno   due  ” indicando per ogni carattere se ti trovi fuori o dentro una parola.',
        'Gestisci null, inizializza il conteggio e scegli uno stato booleano che descriva la posizione corrente.',
        'Quando leggi un carattere non spazio mentre sei fuori, hai trovato l’inizio di una nuova parola: conta una sola volta e cambia stato.',
        'Quando leggi uno spazio, torna nello stato fuori; gli altri caratteri continuano la parola corrente.',
        'Aggiungi chiamate di prova nel main e verifica anche stringa vuota, soli spazi e parole di un carattere.',
      ],
      constraints: [
        'Non usare split(), trim(), Stream o espressioni regolari: il risultato deve derivare dalle transizioni di stato.',
        'In questa missione è separatore soltanto il carattere spazio \' \'; tab e a capo restano fuori dal contratto base.',
        'Per null lancia IllegalArgumentException; non accedere a text prima della validazione.',
      ],
      examples: [
        { input: '"Java si impara"', output: '3', purpose: 'Tre gruppi separati da uno spazio.' },
        { input: '"  uno   due  "', output: '2', purpose: 'Spazi multipli e ai bordi.' },
        { input: '"   "', output: '0', purpose: 'Nessun ingresso nello stato “dentro”.' },
        { input: 'null', output: 'IllegalArgumentException', purpose: 'Caso non valido esplicito.' },
      ],
      acceptance: [
        'Il conteggio aumenta soltanto nella transizione fuori → dentro.',
        'Spazi consecutivi, iniziali e finali non alterano il risultato.',
        'Il metodo gestisce correttamente testo vuoto, soli spazi e null.',
      ],
      reflection: 'Perché contare i caratteri non spazio darebbe un risultato diverso dal numero di parole? Descrivi un input che dimostri la differenza.',
      challenge: 'Estendi il contratto affinché tab e a capo siano separatori usando Character.isWhitespace, poi aggiungi almeno due nuovi test.',
    },
    {
      method: 'reverse',
      title: 'Missione C · Inverti il testo',
      signature: 'static String reverse(String text)',
      scenario: 'L’ultima funzione dell’analizzatore deve creare un’anteprima speculare del testo. La String originale deve restare invariata e il risultato va costruito carattere per carattere.',
      goal: 'Aggiungi un metodo che restituisca una nuova String con i caratteri in ordine inverso. Se text è null, lancia IllegalArgumentException.',
      steps: [
        'Scrivi gli indici di “Java” e stabilisci da quale posizione deve partire la lettura all’indietro.',
        'Dopo la validazione crea un solo StringBuilder vuoto prima del ciclo.',
        'Visita gli indici dall’ultimo valido fino a 0 e aggiungi al builder il carattere corrente.',
        'Converti il builder in String soltanto al termine dell’iterazione.',
        'Verifica il risultato con più caratteri, un solo carattere, String vuota e null.',
      ],
      constraints: [
        'Usa un ciclo indicizzato e StringBuilder per rendere visibile la direzione dell’algoritmo.',
        'Non usare StringBuilder.reverse(), collezioni o scorciatoie equivalenti.',
        'Non modificare text; per null lancia IllegalArgumentException.',
      ],
      examples: [
        { input: '"Java"', output: '"avaJ"', purpose: 'Caso normale con quattro caratteri.' },
        { input: '"A"', output: '"A"', purpose: 'Primo caso limite sugli indici.' },
        { input: '""', output: '""', purpose: 'Nessun indice valido da visitare.' },
        { input: 'null', output: 'IllegalArgumentException', purpose: 'Validazione prima dell’elaborazione.' },
      ],
      acceptance: [
        'Il risultato contiene esattamente gli stessi caratteri in ordine opposto.',
        'String di lunghezza zero e uno non causano errori di indice.',
        'L’implementazione usa un solo builder e rifiuta null come richiesto.',
      ],
      reflection: 'Perché il primo indice è text.length() - 1? Spiega anche perché lo stesso valore rende sicura la String vuota.',
      challenge: 'Usa il metodo per verificare se una parola è palindroma ignorando maiuscole e minuscole, senza cambiare reverse().',
    },
  ] satisfies LabMission[],
} satisfies CourseLesson;
